### ISSUE TITLE
0.4.7 breaks absolute paths

### ISSUE THREAD

**Issue by mjsmagalhaes** [electron-vite/vite-plugin-electron#10]
using absolute paths as entry (both main and preload) used to work until 0.4.5 but now breaks after 0.4.7 upgrade.

**Comment by caoxiemeihao** [comment]
😅

**Comment by mjsmagalhaes** [comment]
https://gitlab.com/mjsmagalhaes/demo-vite-electron

As it is version 0.4.7 will install and fail to build.

cd game
npx vite build

to check. If will rollback to version 0.4.5 and run again it will build without a problem.

**Comment by caoxiemeihao** [comment]
Now, you can try use `vite-plugin-electron` [v0.4.8](https://github.com/electron-vite/vite-plugin-electron/blob/main/CHANGELOG.md#2022-06-08-v048) to resolve the BUG 🐞

**Comment by mjsmagalhaes** [comment]
Thank you!
