### ISSUE TITLE
rollup-plugin-dynamic-import-variables

### ISSUE THREAD

**Issue by yafeng33** [electron-vite/vite-plugin-electron#100]
我用的是0.9.3版本的插件，我想在主进程中动态加载api文件夹下的所有ts文件，它会报rollup-plugin-dynamic-import-variables错误。代码如下：
`const modules = import.meta.glob("./api/**/*.ts", { eager: true });
const fun_map: Record<string, Function> = {};
Object.keys(modules).forEach((key) => {
    Object.keys(modules?.[key]).forEach((k) => {
        if ("function" === typeof modules?.[key]?.[k]) {
            fun_map[k] = modules[key][k];
        }
    });
});
export default fun_map;`
看大家谁遇到这种问题没

**Comment by caoxiemeihao** [comment]
你这写法不需要插件，Vite 本就支持

**Comment by yafeng33** [comment]
你是对的，我这是引入axios插件造成的问题，谢谢！
