### ISSUE TITLE
Not working with Nuxt3

### ISSUE THREAD

**Issue by gimyboya** [electron-vite/vite-plugin-electron#103]
I am trying to use this plugin with nuxt 3 but can't make it work so far. I have the following `nuxt.config.ts`

```ts
import { rmSync } from "fs";
import electron from "vite-electron-plugin";
import renderer from "vite-plugin-electron-renderer";

rmSync("dist-electron", { recursive: true, force: true });

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  ssr: false,
  vite: {
    plugins: [
      electron({
        include: ["electron"],
      }),
      // Use Node.js API in the Renderer-process
      renderer({
        nodeIntegration: true,
      }),
    ],
  },
});

```

and my folder structure is as advised:

```
.
├── README.md
├── app.vue
├── dist
├── electron
│   ├── electron-env.d.ts
│   ├── main.ts
│   └── preload.ts
├── nuxt.config.ts
├── package.json
├── public
│   └── favicon.ico
├── tsconfig.json
└── yarn.lock
```

I am getting the following error: 
```bash
 ERROR  Cannot start nuxt:  Cannot read property 'on' of null                                                  04:25:23

  at configureServer (node_modules/vite-electron-plugin/index.mjs:332:25)
  at Module.createServer (node_modules/vite/dist/node/chunks/dep-4da11a5e.js:62251:30)
  at async buildClient (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.8e427c63.mjs:297:24)
  at async bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.8e427c63.mjs:853:3)
  at async build (node_modules/nuxt/dist/index.mjs:2084:5)
  at async Promise.all (index 1)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6785:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6828:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
  ```
  
  The on refers to the [`httpServer` at this line of code here](https://github.com/electron-vite/vite-plugin-electron/blob/05148dc5d3ef901f4918186d109a02d3fa72f441/packages/electron/src/index.ts#L54)
  
  Not sure how to solve this issue

**Comment by caoxiemeihao** [comment]
Can you provide a minimal production Demo?

**Comment by gimyboya** [comment]
Here is a [minimal reproduction demo](https://stackblitz.com/edit/nuxt-starter-aqydfs). but i came to realize that there are two plugins `vite-plugin-electron` and `vite-electron-plugin` not sure what's the difference between the two (I would appreciate if you can explain the difference to me) but both give me the same error.

**Comment by caoxiemeihao** [comment]
Hi here! 👋
I'm sorry I've been busy lately. I'll find a solution tomorrow morning.

**Comment by CharlesBT** [comment]
Hi guys, I looking for a solution also to have Nuxt3 working, many thanks for your efforts

**Comment by caoxiemeihao** [comment]
I'm very sorry, I've been very, very busy lately!
I didn't really consider **nuxt** compatibility before, thanks to the simplicity of `vite-plugin-electron` design, and currently plan to expose enough API in `0.10.3` to ensure that users can control the enablement of the Electron App in a NodeJs API programming way.
I've provided a demo for use in nuxt here, and may plan a better implementation later.

As for `vite-electron-plugin`, we plan to expose enough APIs for users in the next release.

**Comment by caoxiemeihao** [comment]
@Here! 👋

I have provided a temporary solution based on `vite-plugin-electron@0.10.3`. I plan to add better `nuxt` support in the near future.

**nuxt.config.ts**

```ts
import type { AddressInfo } from 'net'
import { build, startup } from 'vite-plugin-electron'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  ssr: false,
  vite: {
    server: {
      middlewareMode: false,
    },
  },
  hooks: {
    // For development
    listen(server) {
      const addressInfo = server.address() as AddressInfo
      Object.assign(process.env, {
        // This is required, and it is used in Electron-Main.
        VITE_DEV_SERVER_URL: `http://localhost:${addressInfo.port}`,
      })
      build(
        {
          entry: 'electron/main.ts',
          vite: {
            build: { minify: false, watch: {} },
            plugins: [{
              name: 'start-electron-app',
              writeBundle() { startup() },
            }],
          },
        },
      )
    },
    // For build
    'build:done'() {
      if (process.env.NODE_ENV === 'production') {
        build({ entry: 'electron/main.ts' })
      }
    }
  },
})
```

**Comment by gimyboya** [comment]
Thanks a lot @caoxiemeihao I can confirm that it is working on my side. I have one more question please. What's the difference between `vite-plugin-electron` and `vite-electron-plugin` and why should i use one over the other for example?

**Comment by caoxiemeihao** [comment]
**vite-plugin-electron** *vs* **vite-electron-plugin**

1. They are both very simple. Just a simple configuration of the entry file is all that is needed.
2. They both listen for changes to the file and execute `electron .` command to start or restart the Electron App.
3. `vite-plugin-electron` uses Vite builds such as Main-Process, Preload-Scripts, which are based on the build API provided by Vite, which means it works well with all of **Vite's ecosystems**.
`vite-electron-plugin` is much faster(Not Bundle), it is only based on `esbuild` to convert `.ts` files, so its performance is **very high**. It has a plugin system that references Vite's implementation, but is not compatible with Vite's plugins.

**Comment by caoxiemeihao** [comment]
I have written a special plugin for Nuxt3 👉 [nuxt-plugin-electron](https://github.com/caoxiemeihao/nuxt-plugin-electron)

**Comment by gimyboya** [comment]
Thanks @caoxiemeihao ! will use it now if i have any issues will open it in the respective repo
