### ISSUE TITLE
使用0.10.3添加sqlite3，打包后无法运行

### ISSUE THREAD

**Issue by shuyuTech** [electron-vite/vite-plugin-electron#109]
### 案例地址

[案例地址](https://github.com/shuyuTech/quick-start-sqlite3)

### 运行报错的图片

![image](https://user-images.githubusercontent.com/13694788/202343942-72289fbe-28a6-4537-9f08-487414c01458.png)

**Comment by caoxiemeihao** [comment]
`.npmrc` 里面加下 `shamefully-hoist=true`
