### ISSUE TITLE
请问如何将静态文件打包到dist/中

### ISSUE THREAD

**Issue by EvanMeek** [electron-vite/vite-plugin-electron#110]
我的electron代码解构如下:

![图片](https://user-images.githubusercontent.com/27056033/202643573-4650ffa4-3a53-4fef-9c3b-22b5d8aa9d66.png)

我想让其中的protobuf/dialog.proto生成到最终的dist目录里，但我不知道如何配置。请问要如何配置才能实现呢，谢谢草鞋大大

**Comment by caoxiemeihao** [comment]
这个放到 `public` 文件文件夹中，就会自动搬运到 `dist` 中 -- 这是是 Vite 的默认行为。
或者可以试试社区的插件 https://www.npmjs.com/package/vite-plugin-static-copy

**Comment by EvanMeek** [comment]
> 将文件放到 `public` 文件夹中，就会自动搬运到 `dist` 中 -- 这是是 Vite 的默认行为。 或者可以试试社区的插件 https://www.npmjs.com/package/vite-plugin-static-copy

public文件夹貌似只有在vite build才会到dist中，我试试第二个方法吧，谢谢草鞋~

**Comment by caoxiemeihao** [comment]
或者，可以将目录放到 `files` 中，这样就会被 electron-builder 收录
https://github.com/electron-vite/vite-plugin-electron/blob/c7661fa73ecc8561ad0dc81ff82a499b3b3cb3d8/examples/quick-start/electron-builder.json5#L10-L13
