### ISSUE TITLE
Can't run main after migrating to the v0.10

### ISSUE THREAD

**Issue by kpostekk** [electron-vite/vite-plugin-electron#113]
After upgrading to the vite-plugin-electron to the version v0.10.3 I have got a following error.

![image](https://user-images.githubusercontent.com/30326322/204742750-f27e6378-0b4c-42ad-b14b-724a710c327e.png)

I was unable to track down dependecy/module which may cause this behaviour, but I tested various versions of vite and this plugin, and only changing version of this plugin to v0.9 fixes the issue.

**Comment by kpostekk** [comment]
Packages that i use
![image](https://user-images.githubusercontent.com/30326322/204749950-47dfe124-8896-423c-bead-cf0d88cd4193.png)

Options
![image](https://user-images.githubusercontent.com/30326322/204750016-eefaff66-5a0a-4e2f-b6f8-a071c596efec.png)

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction Demo?

**Comment by kpostekk** [comment]
> Can you provide a minimal reproduction Demo?

I will try provide one ASAP

**Comment by kpostekk** [comment]
Fixed by v0.11
