### ISSUE TITLE
dist-electron\main\index.js not exist app.asar问题

### ISSUE THREAD

**Issue by yangdezuan** [electron-vite/vite-plugin-electron#114]
你好，升级后最近发现打包的时候出现 这个问题， 之前是正常的。
⨯ Application entry file "dist-electron\main\index.js" in the "I:\wm\web\dev\electron\pwlivetest\release\1.0.1\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "dist-electron\main\index.js" in the "I:\wm\web\dev\electron\pwlivetest\release\1.0.1\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.

**Comment by xingyue52077** [comment]
同样的问题，是由于将构建文件默认生成到了`dist-electron`文件夹中，在`package.json`中`build`的`files`中只包含了`dist`文件夹，而`dist`文件夹没有`electron`构建的入口文件所导致，目前的解决办法是将`dist-electron`文件夹复制到`dist`中，且将`package.json`的`main`指向新的位置，如`"main": "dist/dist-electron/main.js"`, 之后在打包就可以解决报错问题，我想提问旧版本是默认到`dist`文件夹的，新版本如何修改`electron`的`build`的位置直接到`dist`目录下。

**Comment by caoxiemeihao** [comment]
将 dist-electron 放到 electron-builder.json5 中的 files 中即可。可以参考最新的示例代码。

**Comment by xingyue52077** [comment]
采用这种方法，打包可以成功，不知道为什么运行起来是白屏。。。
