### ISSUE TITLE
[extraResources ] : 想问下vite如何处理特殊静态文件的

### ISSUE THREAD

**Issue by RSS1102** [electron-vite/vite-plugin-electron#124]
我有一个*.dll的文件，我使用相对路径引用他，但是打包的时候*.dll没有被打包进去。导致文件索引不到。
看到[掘金](https://juejin.cn/post/6844904161671118855)这个文章提到了使用extraResources，想问在vite下如何进行配置呢。

**Comment by caoxiemeihao** [comment]
`*.dll` 放到一个文件夹中，然后加入到 `electron-builder.json5` 的 `files` 字段中就可以了。

**Comment by RSS1102** [comment]
> `*.dll` 放到一个文件夹中，然后加入到 `electron-builder.json5` 的 `files` 字段中就可以了。

对于build可以。想问在dev情况下有什么好的办法嘛？我在dist-electron没有找到*.dll。

**Comment by caoxiemeihao** [comment]
干嘛要拘泥于 diss-electron，直接平行不就好了
非要放进去需要 vite 相关插件

**Comment by RSS1102** [comment]
> 

使用了 *.dll,运行正常，但是在打包过程中出现了问题。
配置：
![image](https://user-images.githubusercontent.com/81673017/212039859-3b5d92c3-a487-4b74-be9d-119c4e6be7aa.png)

打包之后的文件夹：
![image](https://user-images.githubusercontent.com/81673017/212039965-41668ecc-49ca-4206-b8c3-ecf97fffbd55.png)

生产环境下的错误：
![image](https://user-images.githubusercontent.com/81673017/212040095-5f744433-8f48-45f2-af32-b489d8184b98.png)
---

好像并没有将这个文件夹下的dll打包进去？

**Comment by caoxiemeihao** [comment]
`libs/**` 试下

**Comment by RSS1102** [comment]
> `libs/**` 试下
依然无法奏效。
但是我在这里我找了解决方法。
https://github.com/electron-userland/electron-builder/issues/7015
```json5

  "win": {
     extraFiles: [
      { from: "libs", to: ".", filter: ["*.dll"] },
    ],

```
