### ISSUE TITLE
Cannot find type definition file for 'vite-plugin-electron/electron-env'

### ISSUE THREAD

**Issue by electronfriends** [electron-vite/vite-plugin-electron#126]
In the examples, an invalid definition for electron-vite-plugin is set in `tsconfig.json`.

The following error occurs when CircleCI runs the command `npm run build`:

```
error TS2688: Cannot find type definition file for 'vite-plugin-electron/electron-env'.
  The file is in the program because:
    Entry point of type library 'vite-plugin-electron/electron-env' specified in compilerOptions
```

I use TypeScript 4.9.5 and vite-plugin-electron 0.11.1

**Comment by caoxiemeihao** [comment]
https://www.npmjs.com/package/vite-plugin-electron?activeTab=explore

<img width="470" alt="image" src="https://user-images.githubusercontent.com/26263658/216743406-d2c32172-7b1e-486e-a5b4-eb09447acef1.png">

**Comment by electronfriends** [comment]
The file does indeed exist, but is still not recognized by TypeScript.

**Comment by caoxiemeihao** [comment]
@electronfriends Hey! 👋
In the latest code(examples/quick-start), this BUG may be fixed.
