### ISSUE TITLE
`Could not resolve entry module "index.html"` when trying to build

### ISSUE THREAD

**Issue by jthrilly** [electron-vite/vite-plugin-electron#128]
Hello

I'm trying to use your plugin, but I receive the following error when running `vite build`: `Could not resolve entry module "index.html"`. 

Configuration:

```
export default defineConfig({
  plugins: [
    electron([
      {
        // Main-Process entry file of the Electron App.
        entry: 'src/main.ts',
      },
      {
        entry: 'src/preload.ts',
        onstart(options) {
          // Notify the Renderer-Process to reload the page when the Preload-Scripts build is complete, 
          // instead of restarting the entire Electron App.
          options.reload()
        },
      },
    ]),
  ],
})
```

If I replace your plugin with vanilla vite configuration, using the `lib` option, I do not receive an error. Seems to be the same as #97 which you closed without a resolution. The configuration I am using is taken directly from the examples.

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?

**Comment by jthrilly** [comment]
Yes, here you go: https://github.com/jthrilly/vite-plugin-electron-reproduction

You will notice that I am only trying to bundle the files for the electron main (backend) process. This is because I am operating in a monorepo, with the frontend in a separate package. I don't see a reason that this shouldn't be a supported use-case.

You can see also that the `dev` task works as expected (except that obviously it does not resolve the frontend).

One final piece of info: if I add a separate `build` section to my config that duplicates the content of `plugins.electron([{vite.build}])`, the build process works.

**Comment by caoxiemeihao** [comment]
You onlywant to run the Main-process, and event the Renderer-process doesn't need Vite support.
Tihs is currently possible with the JavaScript API provided by `vite-plugin-electron`, but the requires secondary scripts.
If you are willing to wait, I can develop a new version for this that supports the Main-process only mode.

**Comment by jthrilly** [comment]
Yes - essentially, I just want this plugin to provide a convenient vite preset for the lib option, and then to handle launching electron. The renderer thread is handled by a separate vite config in another workspace of my monorepo.

I'm very happy to wait, and also to contribute if you are able to let me know what the rough implementation plan would be.

Thanks for your support!

**Comment by caoxiemeihao** [comment]
At present, maybe the [JavaScript API](https://github.com/electron-vite/vite-plugin-electron#javascript-api) is better for you :)
https://github.com/electron-vite/vite-plugin-electron/tree/main/examples/javascript-api

**Comment by jthrilly** [comment]
I can definitely work with the JS API, thank you.

However I do think the behavior I am seeing feels a little "wrong", based on the fact that the plugin configuration implies that vite is operating in lib mode, and therefore shouldn't be concerned with anything other than the specified entrypoints. From an end-user perspective, it isn't clear why `index.html` is even relevant with the above config.

It is especially confusing/inconsistent that this should work in dev mode but not with `build`.

**Comment by caoxiemeihao** [comment]
`vite serve` will try to find the entry file, except when we force a change in VIte's devault vehavior.
https://github.com/vitejs/vite/blob/v4.1.0/packages/vite/src/node/cli.ts#L103-L106
Otherwise we need to ask the user to actively modify the npm command.
```diff
- "dev": "vite"
+ "dev": "vite build --watch"
```
But that doesn't mean that `vite-plugin-electron` will work, it still needs to be modified for that too.

In general, refacotr `vite-plugin-electron` is not a good idea, and I even want to re-release a new plugin for it.
