### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by yuan236** [electron-vite/vite-plugin-electron#129]
Hi, My English is poor, If there is a misnomer, Please forgive me, My envenvironmentis vite & electron 23.1.3, I used jimp in my project. [In the process of using, arise ReferenceError: self is not defined ; After vite-plugin-electron version 10. Dear author, How can I fix it?

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repository?

**Comment by yuan236** [comment]
Thank you very much for your reply!!
```javascript
# npm install jimp -S
import Jimp from 'jimp'
......   
    if (app.isPackaged) {
        win.loadFile(indexHtml)
    } else {
        win.loadURL(url)
        // Open devTool if the app is not packaged
        win.webContents.openDevTools()
    }
    win?.show()

    console.log(Jimp)
```
like this, log jimp throw ReferenceError: self is not defined;
it is it should be 'this'  but not 'self' ?

**Comment by yuan236** [comment]
Before version 0.10 No problem，bug version 0.9.x not supported utilityProcess.fork，so，I modified your dist being used

**Comment by caoxiemeihao** [comment]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/26263658/226556423-cf19f049-d80f-4451-86fc-f5b3a9ccdf54.png">

You can try use the `import Jimp from 'jimp'`

**Comment by yuan236** [comment]
oh god! It was so simple, Thank you
