### ISSUE TITLE
XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by iccyuer** [electron-vite/vite-plugin-electron#13]
mian 主进程中使用axios，提示XMLHttpRequest is not defined

**Comment by caoxiemeihao** [comment]
啊~你们这帮小白；怎么懒成这样 😤

[electron main 中使用axios报错 XMLHttpRequest is not defined](https://github.com/electron-vite/vite-plugin-electron-quick-start/issues/1)

**Comment by iccyuer** [comment]
> 啊~你们这帮小白；怎么懒成这样 😤；麻利儿给我项目都点个⭐️，我考虑原谅你
> 
> [electron main 中使用axios报错 XMLHttpRequest is not defined](https://github.com/electron-vite/vite-plugin-electron-quick-start/issues/1)

非常感谢，  已⭐️
