### ISSUE TITLE
新版感觉更难用了

### ISSUE THREAD

**Issue by meesii** [electron-vite/vite-plugin-electron#130]
之前的版本配置可以用的，切换到新版竟然配置不起来了。
文档也找不到

**Comment by meesii** [comment]
比如electron里面的vite是什么作用？是不是原来vite的配置都要写在里面，都没有进行一个说明。
配置的alias在新版也失效了

**Comment by caoxiemeihao** [comment]
新版本再稳定一段时间，等到 electron forge 发版后会作为 1.0.0 发布
