### ISSUE TITLE
打包后依赖的依赖找不到

### ISSUE THREAD

**Issue by 984035589** [electron-vite/vite-plugin-electron#131]
开发时正常
打包后，依赖的依赖找不到，比如我的package.json中依赖了log4js，log4js的package.json依赖了date-format，打包之后提示 Cannot find module 'date-format'

**Comment by 984035589** [comment]
麻烦看下，谢谢大佬
[demo.zip](https://github.com/electron-vite/vite-plugin-electron/files/11041825/demo.zip)

**Comment by caoxiemeihao** [comment]
`.npmrc` 文件中加下 pnpm 配置

```sh
shamefully-hoist=true
```

**Comment by 984035589** [comment]
顶礼膜拜！

**Comment by caoxiemeihao** [comment]
可以扫码赞助 😂

**Comment by 984035589** [comment]
小赞助了一下😄

**Comment by caoxiemeihao** [comment]
优秀 👍
