### ISSUE TITLE
electron 装了部分包后，后台部分热更新失败

### ISSUE THREAD

**Issue by meedfine** [electron-vite/vite-plugin-electron#132]
https://github.com/meedfine/electron-hmr-fail

只有一个提交记录
安装electron-devtools-installer  electron-store
npm run dev,然后修改main进程的配置，如title或宽高等等，只要触发hmr即可，然后进程就卡住了，无法自动重启app

**Comment by meedfine** [comment]
且装了这些后，启动构建 都会慢很多

**Comment by ewigl** [comment]
请问关闭了issue是问题得到解决了吗，我使用electron-store也遇到了同样的问题，请教下解决方案

**Comment by caoxiemeihao** [comment]
issue 重复
https://github.com/electron-vite/electron-vite-vue/issues/359
