### ISSUE TITLE
(Question) Possible to target all files within a folder?

### ISSUE THREAD

**Issue by JacobWennebro** [electron-vite/vite-plugin-electron#133]
Is it possible to tell vite-plugin-electron to build all files within a certain folder rather than having to explicitly target them by name? I am building an application that should be able to load external plug-in files from a folder, which would be in js but being able to develop them in ts with the application source is a far better experience :)

**Comment by caoxiemeihao** [comment]
Maybe you the [vite-electron-plugin](https://github.com/caoxiemeihao/vite-electron-plugin) better for you :)

<img width="510" alt="image" src="https://user-images.githubusercontent.com/26263658/229676053-cb83d6f5-e15f-4f3c-bd72-cd8e1e01b8e4.png">
