### ISSUE TITLE
Trying to use `axios` in the main process fails

### ISSUE THREAD

**Issue by CommandMC** [electron-vite/vite-plugin-electron#136]
Hello there! We're using this plugin in [Heroic-Games-Launcher/HeroicGamesLauncher](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher), currently with great success. However, after trying to update to v4 version of Vite (and with that, the latest version of this plugin), `axios`, our preferred HTTP client, is no longer working.  
The exact error message (encountered when trying to do any request via `axios.get`) is `Error: Adapter 'http' is not available in the build`. I've also created a minimal example here: [CommandMC/electron-vite-axios](https://github.com/CommandMC/electron-vite-axios). I've found various similar-sounding issues about this online, but none of the proposed solutions there (adding various other plugins, marking the package as `external`) worked.

One possible solution to this would of course be to just *not use `axios`* (Node 18 features a `fetch` implementation that works basically the same way, after all), however this is sadly not an option here.

**Comment by caoxiemeihao** [comment]
```diff
import { defineConfig } from 'vite'
import electron from 'vite-plugin-electron'

export default defineConfig({
  plugins: [
    electron([
      {
        // Main-Process entry file of the Electron App.
        entry: 'electron/main.ts',
+       vite: {
+         resolve: {
+           browserField: false,
+         },
+       },
      },
    ]),
  ],
})
```

- [ ] `v0.11.2` will be configure is by default :)

**Comment by CommandMC** [comment]
I see, thanks for the quick fix! I've noticed that this same change was also introduced in #98, but it seems those changes got lost somewhere.

**Comment by caoxiemeihao** [comment]
Okay so sorry! I think Vite will be remove this option because it was depreciate in Vite :( 
Unfortunately it still can be used 😖
