### ISSUE TITLE
preload.js 文件不拆分

### ISSUE THREAD

**Issue by ggymm** [electron-vite/vite-plugin-electron#141]
vite.config.ts配置
```javascript
{
  entry: 'electron/preload/view.ts',
  vite: {
    build: {
      outDir: 'build/dist-electron/preload',
      minify: true,
      sourcemap: false,
      rollupOptions: {
        output: {
          manualChunks: undefined
        }
      }
    }
  },
  onstart(options) {
    options.reload()
  }
}
```

preload文件夹输出
![image](https://github.com/electron-vite/vite-plugin-electron/assets/20694755/7787dc18-d6c3-4907-9bfe-dc4ce07397ed)

想让electron/preload/view.ts的输出文件为单个build/dist-electron/preload/view.js

因为在electron的在开启了sandbox开启时，preload不能require除了electron，node之外的包。所以打包拆分之后会导致
view-a17d7368.js文件无法加载

**Comment by caoxiemeihao** [comment]
```diff
- manualChunks: undefined
+ manualChunks: {}
```

试试看行不行，不行提供一个复现的 Demo 仓库

**Comment by ggymm** [comment]
你好，重现仓库，可以看我最近一次提交内容就是修改内容
https://github.com/ggymm/electron-vite-vue-test

**Comment by neostfox** [comment]
遇到同样的问题。

**Comment by neostfox** [comment]
> ```diff
> - manualChunks: undefined
> + manualChunks: {}
> ```
> 
> 试试看行不行，不行提供一个复现的 Demo 仓库

``` ts
          vite: {
              rollupOptions: {
                output: {
                  inlineDynamicImports: true
                },
                external: Object.keys(
                  "dependencies" in pkg ? pkg.dependencies : {}
                ),
              },
            },
```

配置 vite.rollupOptions.output.inlineDynamicImports 为true可以解决异步引入合并的问题。其他的情况，可以参考 rollup 的文档。
manualChunks 已经废弃了
