### ISSUE TITLE
Uncaught Error: Dynamic require of "fs/promises" is not supported  

### ISSUE THREAD

**Issue by lwb-2021** [electron-vite/vite-plugin-electron#142]
如题所示，当我打开contextIsolation时报错
![图片](https://github.com/electron-vite/vite-plugin-electron/assets/91705377/2e7ba52e-15c3-4d71-acfa-662798439dcb)
在vite转换后的文件发现了这一行，而electron不支持require，现有的插件都不能很好的识别并替换这里，请问能否做出相应的功能？
![图片](https://github.com/electron-vite/vite-plugin-electron/assets/91705377/d618652e-fc0b-4513-89de-0b344a203ad9)

**Comment by caoxiemeihao** [comment]
Electron 不支持 `require`？你逗我？

**Comment by lwb-2021** [comment]
……不是很确定，但是大概率是的，因为他就是这么报错的（应该是vite翻译的问题，把渲染线程里面搞了一个require进去）



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月26日 22:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [electron-vite/vite-plugin-electron] Uncaught Error: Dynamic require of "fs/promises" is not supported (Issue #142) |

Electron 不支持 require？你逗我？

**Comment by mcode-top** [comment]
可以尝试下关闭沙盒模式,或者contextIsolation设置为false,https://www.electronjs.org/docs/latest/tutorial/context-isolation
