### ISSUE TITLE
如何取消renderer()预构建

### ISSUE THREAD

**Issue by zxlisrich** [electron-vite/vite-plugin-electron#144]
加载不到相应的模块
![image](https://github.com/electron-vite/vite-plugin-electron/assets/54522716/3a9ae1d6-a01a-4701-83df-78ca859a8da0)

**Comment by zxlisrich** [comment]
又换了个报错了 
![image](https://github.com/electron-vite/vite-plugin-electron/assets/54522716/6eb6dc3f-370c-45b0-b9dc-9c7cc8bfac99)

**Comment by caoxiemeihao** [comment]
我推荐你用这个 quick-start 模板 https://github.com/electron-vite/vite-plugin-electron-renderer/tree/main/examples/quick-start
或者 `electron-vite-vue`
