### ISSUE TITLE
请教一下，我该如何打包这些外部依赖，作为外部依赖后，开发正常，打包后就报错了。

### ISSUE THREAD

**Issue by yaoshengli** [electron-vite/vite-plugin-electron#147]
![1691307749522](https://github.com/electron-vite/vite-plugin-electron/assets/13297623/4a17397e-a78f-4ebd-86cf-3d5b07a8f5d8)

**Comment by caoxiemeihao** [comment]
作为外部依赖后，构建期必须放到 `dependencies` 才能行，你试试。

**Comment by yaoshengli** [comment]
已经在dependencies里，打包后会报找不到模块之类的错误，开发环境却正常。
![1691315419624](https://github.com/electron-vite/vite-plugin-electron/assets/13297623/9485ed9f-3654-4592-9c89-0f96cc74f152)

**Comment by so1ve** [comment]
能给一个repro吗

**Comment by yaoshengli** [comment]
是这样的，我本意是想渲染层使用开源项目[vben-admin](https://github.com/vbenjs/vue-vben-admin)，结合插件vite-plugin-electron开发electron项目，然后主进程层使用开源项目[fast-vite-nestjs-electron](https://github.com/ArcherGu/fast-vite-nestjs-electron)，这样可以使用nestjs的方式来写主进程的node代码，方便维护。结果渲染层很顺利就结合了，主进程层引入依赖后，照猫画虎后，开发模式正常，打包就报错了。vben规定只能使用pnpm。（小白瞎折腾）

**Comment by yaoshengli** [comment]
我测试了[electron-vite-vue](https://github.com/electron-vite/electron-vite-vue)，使用[fast-vite-nestjs-electron](https://github.com/ArcherGu/fast-vite-nestjs-electron)的时候，用yarn安装并打包，正常，使用pnpm安装并打包，会报错。估计现在打包不支持pnpm。

**Comment by so1ve** [comment]
`.npmrc` 里头写上 `samefully-hoist=true`

**Comment by yaoshengli** [comment]
pnpm dev 正常
![1691388845963](https://github.com/electron-vite/vite-plugin-electron/assets/13297623/e5b26a31-a858-4a60-bf1b-4e75ee23d250)
pnpm build 会报错
![1691388903721](https://github.com/electron-vite/vite-plugin-electron/assets/13297623/c4a2b5ee-1e5d-4314-a641-b289b3670c18)
只增加了新的依赖和index文件的引入
![image](https://github.com/electron-vite/vite-plugin-electron/assets/13297623/5cbbf24e-fa57-4fed-92e2-8c09a5123525)
![image](https://github.com/electron-vite/vite-plugin-electron/assets/13297623/ea28fa6c-5a85-4f52-a289-4c1450a44b0e)

**Comment by caoxiemeihao** [comment]
感觉你这有点离谱，你要么手动控制下 `external`，默认是把 `dependencies` 中全部 `external` 了
<img width="602" alt="image" src="https://github.com/electron-vite/vite-plugin-electron/assets/26263658/b6c5d236-50f9-4f34-aadb-52c255bb8ce4">
