### ISSUE TITLE
关于 dist-electron 其它js文件路径问题

### ISSUE THREAD

**Issue by Canees** [electron-vite/vite-plugin-electron#152]
问题点：
1. 如果electron 中包含了其它js脚本，路径使用的是join(__dirname, './***') 此时dist-electron中又不存在js脚本就会出错，得改路径才能解决
2. 如果package.json的入口文件设置为electron/main.js,,vite.config中设置electron的entry同样为electron/main.js 程序都能正常更新

总结：此时dist-electron感觉就没啥存在必要

**Comment by sky124380729** [comment]
遇到了同样的问题

**Comment by shuyuTech** [comment]
不清楚你的使用方式，但是可以用如下解决
```js
import.meta.globEager("../xx/*.js");
```

**Comment by sky124380729** [comment]
> 

哪里配？

**Comment by sky124380729** [comment]
> 不清楚你的使用方式，但是可以用如下解决
> 
> ```js
> import.meta.globEager("../xx/*.js");
> ```

哪里配？

**Comment by shuyuTech** [comment]
> > 不清楚你的使用方式，但是可以用如下解决
> > ```js
> > import.meta.globEager("../xx/*.js");
> > ```
> 
> 哪里配？

😮，vite基本用法，哪里用，哪里配。https://cn.vitejs.dev/guide/features.html#glob-import

**Comment by caoxiemeihao** [comment]
> 不清楚你的使用方式，但是可以用如下解决
> 
> ```js
> import.meta.globEager("../xx/*.js");
> ```

正解 👍

**Comment by Canees** [comment]
> 狮子的使用方式，但是可以用以下解决
> 
> ```js
> import.meta.globEager("../xx/*.js");
> ```
我说的是electron主进程的js文件，不是vite
![image](https://github.com/electron-vite/vite-plugin-electron/assets/40012261/49715e80-23fd-42b6-9531-b251a33c4fa5)
![image](https://github.com/electron-vite/vite-plugin-electron/assets/40012261/5791bc3c-b942-430b-99f3-6dd39f269ede)
![image](https://github.com/electron-vite/vite-plugin-electron/assets/40012261/8e735779-f675-44e0-9141-528b7eccf7bb)

我这样配置，跟它自动生成的dist-electron没一点关系。

**Comment by caoxiemeihao** [comment]
你可以考虑用 [vite-plugin-static-copy](https://www.npmjs.com/package/vite-plugin-static-copy) 将 `icon` 目录 copy 到 `dist-electron` 或者直接把 `icon` 放到 `electron` 目录外面使用。

**Comment by Canees** [comment]
没必要多装啥插件，eletron的主文件图标等都需要在主进程使用，就单纯觉得多生成的dist-electron 没啥用。
![image](https://github.com/electron-vite/vite-plugin-electron/assets/40012261/f7d56ba3-4fb1-4049-8ee5-64b778afa349)
看了源码，修改配置到dist里面去，不影响electron打包

**Comment by sky124380729** [comment]
> 没必要多装啥插件，eletron的主文件图标等都需要在主进程使用，就单纯觉得多生成的dist-electron 没啥用。 ![image](https://user-images.githubusercontent.com/40012261/261957532-f7d56ba3-4fb1-4049-8ee5-64b778afa349.png) 看了源码，修改配置到dist里面去，不影响electron打包

我换了vite-electron-plugin

**Comment by Canees** [comment]
> > 没必要多装啥插件，eletron的主文件图标等都需要在主进程使用，就单纯觉得多生成的dist-electron 没啥用。 ![image](https://user-images.githubusercontent.com/40012261/261957532-f7d56ba3-4fb1-4049-8ee5-64b778afa349.png) 看了源码，修改配置到dist里面去，不影响electron打包
> 
> 我换了vite-electron-plugin

咋样嘛？我看都是同一个人写的

**Comment by sky124380729** [comment]
> > > 没必要多装啥插件，eletron的主文件图标等都需要在主进程使用，就单纯觉得多生成的dist-electron 没啥用。 ![image](https://user-images.githubusercontent.com/40012261/261957532-f7d56ba3-4fb1-4049-8ee5-64b778afa349.png) 看了源码，修改配置到dist里面去，不影响electron打包
> > 
> > 
> > 我换了vite-electron-plugin
> 
> 咋样嘛？我看都是同一个人写的

作者不就在楼上嘛。我也不知道他为啥整两个，反正入口文件多的问题我暂时使用vite-electron-plugin了，我也看了作者知乎的文章 [一个插件将 Vite 与 Electron 无缝结合](https://zhuanlan.zhihu.com/p/497638546)，后面考虑自己写一个

**Comment by caoxiemeihao** [comment]
去看置顶的 ISSUE
[关于 vite-plugin-electron 与 vite-electron-plugin](https://github.com/electron-vite/vite-plugin-electron/issues/107)

**Comment by sky124380729** [comment]
> 去看置顶的 ISSUE [关于 vite-plugin-electron 与 vite-electron-plugin](https://github.com/electron-vite/vite-plugin-electron/issues/107)

很棒的作者

**Comment by Canees** [comment]
好家伙，-plugin 中引用了-electron 😀

**Comment by caoxiemeihao** [comment]
之前这两个插件共存了很久
`vite-plugin-electron` 用于 `electron-vite-vue`
`vite-electron-plugin` 用于 `electron-vite-react`

后来我加入 Electron 后需要给 [electron-forge](https://github.com/electron/forge) 提交 Vite 支持部分代码，内部商量了几波后最终确定使用 `vite-plugin-electron` 作为原型给 electron-forge 贡献代码。
然后 `vite-electron-plugin` 就被我转移到了我的私人名下不再继续维护，不过它有着极其出色的性能还是让我念念不忘！
于是乎在最新的 [vite-plugin-electron@0.13.0-beta.2](https://github.com/electron-vite/vite-plugin-electron/blob/v0.13.0-beta.2/CHANGELOG.md) 中加了一个 Not Bundle 功能，这样一来性能似乎接近 `vite-electron-plugin` 很多，甚至 `patak-dev` 也很喜欢这个方案。
<img width="606" alt="image" src="https://github.com/electron-vite/vite-plugin-electron/assets/26263658/42206682-9497-4709-ac6d-fdc39f867d5f">
