### ISSUE TITLE
vite-plugin-electron不支持ffi-napi

### ISSUE THREAD

**Issue by Coder-XJ** [electron-vite/vite-plugin-electron#153]
vite-plugin-electron不支持ffi-napi，当我在主进程引入ffi-napi，会将他解析为：
const require$$1$2 = require("assert");
const require$$1 = require("util");
const require$$0 = require("tty");
const require$$0$1 = require("os");
const require$$1$1 = require("path");
const require$$0$2 = require("fs");
const require$$6 = require("buffer");
function getDefaultExportFromCjs(x) {
  return x && x.__esModule && Object.prototype.hasOwnProperty.call(x, "default") ? x["default"] : x;
}
var ffi$1 = {};
var ref$1 = { exports: {} };
var src$1 = { exports: {} };
var browser$1 = { exports: {} };
var ms$1;
var hasRequiredMs$1;
function requireMs$1() {
  if (hasRequiredMs$1)
    return ms$1;
  hasRequiredMs$1 = 1;
  var s = 1e3;
  var m = s * 60;
  var h = m * 60;
  var d = h * 24;
  var w = d * 7;
  var y = d * 365.25;
  ms$1 = function(val, options) {
    options = options || {};
    var type2 = typeof val;
    if (type2 === "string" && val.length > 0) {
      return parse(val);
    } else if (type2 === "number" && isFinite(val)) {
      return options.long ? fmtLong(val) : fmtShort(val);
    }
    throw new Error(
      "val is not a non-empty string or a valid number. val=" + JSON.stringify(val)
    );
  };
  function parse(str) {
    str = String(str);
    if (str.length > 100) {
      return;
    }
    var match = /^(-?(?:\d+)?\.?\d+) *(milliseconds?|msecs?|ms|seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d|weeks?|w|years?|yrs?|y)?$/i.exec(
      str
    );
    if (!match) {
      return;
    }
    var n = parseFloat(match[1]);
    var type2 = (match[2] || "ms").toLowerCase();
    switch (type2) {
      case "years":
      case "year":
      case "yrs":
      case "yr":
      case "y":
        return n * y;
      case "weeks":
      case "week":
      case "w":
        return n * w;
      case "days":
      case "day":
      case "d":
        return n * d;
      case "hours":
      case "hour":
      case "hrs":
      case "hr":
      case "h":
        return n * h;
      case "minutes":
      case "minute":
      case "mins":
      case "min":
      case "m":
        return n * m;
      case "seconds":
      case "second":
      case "secs":
      case "sec":
      case "s":
        return n * s;
      case "milliseconds":
      case "millisecond":
      case "msecs":
      case "msec":
      case "ms":
        return n;
      default:
        return void 0;
    }
  }
  function fmtShort(ms2) {
    var msAbs = Math.abs(ms2);
    if (msAbs >= d) {
      return Math.round(ms2 / d) + "d";
    }
    if (msAbs >= h) {
      return Math.round(ms2 / h) + "h";
    }
    if (msAbs >= m) {
      return Math.round(ms2 / m) + "m";
    }
    if (msAbs >= s) {
      return Math.round(ms2 / s) + "s";
    }
    return ms2 + "ms";
  }
  function fmtLong(ms2) {
    var msAbs = Math.abs(ms2);
    if (msAbs >= d) {
      return plural(ms2, msAbs, d, "day");
    }
    if (msAbs >= h) {
      return plural(ms2, msAbs, h, "hour");
    }
    if (msAbs >= m) {
      return plural(ms2, msAbs, m, "minute");
    }
    if (msAbs >= s) {
      return plural(ms2, msAbs, s, "second");
    }
    return ms2 + " ms";
  }
  function plural(ms2, msAbs, n, name) {
    var isPlural = msAbs >= n * 1.5;
    return Math.round(ms2 / n) + " " + name + (isPlural ? "s" : "");
  }
  return ms$1;
}

.....

**Comment by shuyuTech** [comment]
是支持的

**Comment by Coder-XJ** [comment]
我的会把ff-napi转成这种形式
const require$$1$2 = require("assert");
const require$$1 = require("util");
const require$$0 = require("tty");
const require$$0$1 = require("os");
const require$$1$1 = require("path");
const require$$0$2 = require("fs");
const require$$6 = require("buffer");
function getDefaultExportFromCjs(x) {
return x && x.__esModule && Object.prototype.hasOwnProperty.call(x, "default") ? x["default"] : x;
}
控制台会报错

**Comment by Coder-XJ** [comment]
> 是支持的

我的会把ff-napi转成这种形式
const require$$1$2 = require("assert");
const require$$1$2 = require（“assert”）;
const require$$1 = require("util");
const require$$1 = require（“util”）;
const require$$0 = require("tty");
const require$$0 = require（“tty”）;
const require$$0$1 = require("os");
常量要求$$0$1 = 要求（“OS”）;
const require$$1$1 = require("path");
常量要求$$1$1 = 要求（“路径”）;
const require$$0$2 = require("fs");
常量要求$$0$2 = 要求（“fs”）;
const require$$6 = require("buffer");
常量要求$$6 = 要求（“缓冲区”）;
function getDefaultExportFromCjs(x) {
function getDefaultExportFromCjs（x） {
return x && x.__esModule && Object.prototype.hasOwnProperty.call(x, "default") ? x["default"] : x;
return x && x.__esModule && Object.prototype.hasOwnProperty.call（x， “default”） ？x[“默认”] ： x;
}
控制台会报错

**Comment by shuyuTech** [comment]
electron什么版本？

**Comment by Coder-XJ** [comment]
> electron什么版本？

20.3.8

**Comment by Coder-XJ** [comment]
> electron什么版本？

不使用electron-plugin-electron 就能正确引用ffi-napi，并使用

**Comment by shuyuTech** [comment]
> > electron什么版本？
> 
> 不使用electron-plugin-electron 就能正确引用ffi-napi，并使用

我也在使用这个vite-plugin-electron ，正常使用没有问题。
![image](https://github.com/electron-vite/vite-plugin-electron/assets/13694788/e33ec1fc-754f-4eca-ae0d-e12f7328934e)

**Comment by Coder-XJ** [comment]
> > > electron什么版本？
> > 
> > 
> > 不使用electron-plugin-electron 就能正确引用ffi-napi，并使用
> 
> 我也在使用这个vite-plugin-electron ，正常使用没有问题。 ![image](https://user-images.githubusercontent.com/13694788/260655899-e33ec1fc-754f-4eca-ae0d-e12f7328934e.png)

vite-plugin-electron 有做过什么配置吗，你使用的node版本是多少

**Comment by Coder-XJ** [comment]
> > > electron什么版本？
> > 
> > 
> > 不使用electron-plugin-electron 就能正确引用ffi-napi，并使用
> 
> 我也在使用这个vite-plugin-electron ，正常使用没有问题。 ![image](https://user-images.githubusercontent.com/13694788/260655899-e33ec1fc-754f-4eca-ae0d-e12f7328934e.png)

![image](https://github.com/electron-vite/vite-plugin-electron/assets/64201765/1c49ec0b-a06e-4d52-b306-923a59cd92c8)
会将ffi-napi转成这样的

**Comment by shuyuTech** [comment]
preload.ts？

**Comment by Coder-XJ** [comment]
> preload.ts？ 预加载.ts？

是的，用的ts写法

**Comment by shuyuTech** [comment]
> > preload.ts？ 预加载.ts？
> 
> 是的，用的ts写法

你这么回，仿佛我在期望得到你的肯定答复一样。

**Comment by shuyuTech** [comment]
试试直接在主进程的文件中，加载使用

**Comment by Coder-XJ** [comment]
> 试试直接在主进程的文件中，加载使用

试过了，和上面截图一样

**Comment by shuyuTech** [comment]
> 发一个最小可用的demo出来

发一个最小可用的demo出来看看

**Comment by Coder-XJ** [comment]
> > 发一个最小可用的demo出来
> 
> 发一个最小可用的demo出来看看

https://github.com/Coder-XJ/electron

**Comment by shuyuTech** [comment]
> > > 开发一个最小可用的演示版
> > 
> > 
> > 开发一个最小可用的演示看看
> 
> [https://github.com/Coder-XJ/ Electron](https://github.com/Coder-XJ/electron)

改好了，请查收

![image](https://github.com/electron-vite/vite-plugin-electron/assets/13694788/01186000-9824-4219-863d-38a68017f8d9)
![image](https://github.com/electron-vite/vite-plugin-electron/assets/13694788/c0d53746-579b-4570-9877-f8a933c2d837)

**Comment by Coder-XJ** [comment]
> 好的，谢谢，我对代码进行了修改，没有对ffi-napi进行转码，但是控制台报错如下，是不是我node版本有问题，能问下大佬用的是那个版本的node吗

**Comment by shuyuTech** [comment]
> > 好的，谢谢，我对代码进行了修改，没有对ffi-napi进行转码，但是控制台报错如下，是不是我node版本有问题，能问下大佬用的是那个版本的node吗

？

**Comment by Coder-XJ** [comment]
> > 好的，谢谢，我对代码进行了修改，没有对ffi-napi进行转码，但是控制台报错如下，是不是我node版本有问题，能问下大佬用的是那个版本的node吗
![image](https://github.com/electron-vite/vite-plugin-electron/assets/64201765/b74fe2c7-9244-4f06-8976-bf87050e5880)

**Comment by shuyuTech** [comment]
> > > 好的，谢谢，我对代码进行了修改，没有对ffi-napi进行转码，但是控制台报错如下，是不是我node版本有问题，能问下大佬用的是那个版本的node吗
> > > ![image](https://user-images.githubusercontent.com/64201765/260675129-b74fe2c7-9244-4f06-8976-bf87050e5880.png)

哪个文件中使用的？

**Comment by Coder-XJ** [comment]
> > > > 好的，谢谢，我对代码进行了修改，没有对ffi-napi进行转码，但是控制台报错如下，是不是我node版本有问题，能问下大佬用的是那个版本的node吗
> > > > ![image](https://user-images.githubusercontent.com/64201765/260675129-b74fe2c7-9244-4f06-8976-bf87050e5880.png)
> 
> 哪个文件中使用的？

嗷嗷嗷，不好意思，我渲染进程里面的代码忘记删除了

**Comment by Coder-XJ** [comment]
> > > > 好的，谢谢，我对代码进行了修改，没有对ffi-napi进行转码，但是控制台报错如下，是不是我node版本有问题，能问下大佬用的是那个版本的node吗
> > > > ![image](https://user-images.githubusercontent.com/64201765/260675129-b74fe2c7-9244-4f06-8976-bf87050e5880.png)
> 
> 哪个文件中使用的？

谢谢大佬
