### ISSUE TITLE
How to specify in vite.config.ts file different apps for different windows?

### ISSUE THREAD

**Issue by raphael10-collab** [electron-vite/vite-plugin-electron#16]
How to specify in https://github.com/electron-vite/electron-vite-react/blob/main/vite.config.ts different apps each for a different window?

For example:

    /src/app
    /src/app_A 
    /src/app_B

where `App.tsx` and `main.tsx` are in `/src/app` : 

    /src/app/App.tsx
    /src/app/main.tsx 
    
    /src/app_A/App_A.tsx
    /src/app_A/main_A.tsx
    
    /src/app_B/App_B.tsx
    /src/app_B/main_B.tsx

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/electron-vite-react/issues/37
