### ISSUE TITLE
Electron 26: hot restart proplem

### ISSUE THREAD

**Issue by tadmi** [electron-vite/vite-plugin-electron#162]
On electron 26 at hot restart due to changes in main.ts electron.exe processes fly out into free swimming, load the processor and are not killed by the plugin. There is no problem on version 25.

**Comment by caoxiemeihao** [comment]
https://github.com/caoxiemeihao/electron-vite-samples/tree/main/quick-start

**Comment by tadmi** [comment]
![image](https://github.com/electron-vite/vite-plugin-electron/assets/63556979/022053a4-e1cd-4335-b21b-c74f45a21411)

**Comment by caoxiemeihao** [comment]
Looks like main process can not exit correctly. Can you provide a minimal reproduction repo?

**Comment by tadmi** [comment]
windows 11
node 21

quick-start example

https://github.com/electron-vite/vite-plugin-electron/assets/63556979/42f1a0f0-3981-4b7b-b2f2-1ad9497577c8

**Comment by tadmi** [comment]
There doesn't seem to be a problem if [do as here](https://github.com/cawa-93/vite-electron-builder/blob/4b60afdc8a9058833799c666794743e6e4f27c87/scripts/watch.mjs#L42)

**Comment by tadmi** [comment]
on version 0.15.3 I have not observed this problem yet
