### ISSUE TITLE
模拟客户端实现退出登录(注销/切换账号)的功能异常

### ISSUE THREAD

**Issue by Dickens-Shaw** [electron-vite/vite-plugin-electron#169]
```jsx
// App.tsx 增加一个按钮触发退出登录事件
31+  <button
32+    onClick={() => {
33+     postMessage({ payload: 'logout' }, '*');
34+   }}
35+  >
36+    退出登录
37+  </button>

// preload.ts
window.onmessage = ev => {
  ev.data.payload === 'removeLoading' && removeLoading()
115+  ev.data.payload === 'logout' && ipcRenderer.send('logout');  // 预加载添加logout事件监听，通知主进程退出
}

// main.ts
1+  import { app, BrowserWindow, ipcMain } from 'electron'

// 主进程监听退出消息，触发应用重启[1]
62+  ipcMain.on('logout', () => {
63+   app.relaunch()
64+   app.quit() // or app.exit()
65+  })
```

> *1. 重启应用: [https://www.electronjs.org/docs/latest/api/app#apprelaunchoptions](https://www.electronjs.org/docs/latest/api/app#apprelaunchoptions)

### 环境
平台：  Apple M1，macOS 14.0
node:   v16.14.0
yarn:    1.22.19

### 预期
点击 count 任意次数后点击退出登录按钮，客户端关闭并重启，Web APP重载，count 重置为0

### 实际
点击退出登录按钮后，客户端确实执行了重启操作，但是Vite 的 devServer 直接挂掉，页面出来也就空白了。

麻烦看看能不能复现，然后帮忙确认一下是什么问题导致的呢？是否有主动 shutdown 的操作嘞？

**Comment by Dickens-Shaw** [comment]
```js
```

**Comment by Dickens-Shaw** [comment]
```js
```

**Comment by Dickens-Shaw** [comment]
```js
export async function startup(argv = ['.', '--no-sandbox']) {
  const { spawn } = await import('node:child_process')
  // @ts-ignore
  const electron = await import('electron')
  const electronPath = <any>(electron.default ?? electron)

  startup.exit()
  // Start Electron.app
  process.electronApp = spawn(electronPath, argv, { stdio: 'inherit' })
  // Exit command after Electron.app exits
  process.electronApp.once('exit', process.exit)

  if (!startup.hookProcessExit) {
    startup.hookProcessExit = true
    process.once('exit', startup.exit)
  }
}
startup.hookProcessExit = false
startup.exit = () => {
  if (process.electronApp) {
    process.electronApp.removeAllListeners()
    process.electronApp.kill()
  }
}
```
是不是这个方法的问题？

**Comment by caoxiemeihao** [comment]
> https://github.com/electron-vite/vite-plugin-electron/blob/v0.14.2/src/index.ts#L111

会直接杀死主进程后会再次重新拉起，和 electron 提供的 [app.relaunch([options])](https://www.electronjs.org/docs/latest/api/app#apprelaunchoptions) 是两码事。

你看下主进程中的是不是 `process.env.VITE_DEV_SERVER_URL` 这个环境变量变化了。

**Comment by Dickens-Shaw** [comment]
> > https://github.com/electron-vite/vite-plugin-electron/blob/v0.14.2/src/index.ts#L111
> 
> 会直接杀死主进程后会再次重新拉起，并且 Electron 提供的[app.relaunch([options])](https://www.electronjs.org/docs/latest/api/app#apprelaunchoptions)是两码事。
> 
> 你看下主进程中的不是`process.env.VITE_DEV_SERVER_URL`这个环境变量变化了。

没有哦，就算不使用我增加的按钮逻辑，在Menu菜单里点击Quit也会直接导致devServer和终端关闭呀！

**Comment by caoxiemeihao** [comment]
不确定是不是 electron 自带的菜单中的退出是不是发送了 `SIGKILL` 信号，这个没法在代码中验证。。。
在 electron 源码中能看到相关逻辑

**Comment by Dickens-Shaw** [comment]
![](https://user-images.githubusercontent.com/26263658/279037533-633de3f5-03e0-457b-aeae-fc42605f950b.png)
确实是这个导致的

**Comment by Dickens-Shaw** [comment]
个人观点：
