### ISSUE TITLE
open multiple Renderer windows 

### ISSUE THREAD

**Issue by tokochi** [electron-vite/vite-plugin-electron#17]
how i can add other html files to render as new windows, i have tried adding this code to vite.config.js ;
`  build: {
    input: {
      main: resolve(__dirname, "index.html"),
      worker: resolve(__dirname, "worker.html"),
      toolbar: resolve(__dirname,'toolbar.html')
    },
  },`
  but i dont get any output files in dist/electron/main folder, can you please help me.

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/electron-vite-react/issues/37#issuecomment-1157074322
