### ISSUE TITLE
如何在渲染器中使用session

### ISSUE THREAD

**Issue by Z1oftheKill** [electron-vite/vite-plugin-electron#170]
如何在渲染器中使用session,我想使用session中的cookie 如何在electron中使用cookie呢

**Comment by shuyuTech** [comment]
你的问题和这个项目没有什么关系。

**Comment by Z1oftheKill** [comment]
> 你的问题和这个项目没有什么关系。
我在使用webpack的时候可以直接使用,这个我不知道怎么使用了

**Comment by caoxiemeihao** [comment]
可以在主进程中拦截请求
https://www.electronjs.org/docs/latest/api/web-request
然后手动管理 Cookie
https://www.electronjs.org/docs/latest/api/cookies

---

可以参考下这个项目 👉 https://github.com/Jenny-pyl/music-desktop-application/blob/main/electron/main/web-request.ts
