### ISSUE TITLE
Electron is going to support ESM from 28

### ISSUE THREAD

**Issue by yooouuri** [electron-vite/vite-plugin-electron#172]
https://github.com/electron/electron/pull/37535

🥳

**Comment by caoxiemeihao** [comment]
Yep! electron@28 is awesome 🎉

**Comment by caoxiemeihao** [comment]
[Migration to v0.28.0-beta.1](https://github.com/electron-vite/vite-plugin-electron/blob/v0.28.0-beta.1/CHANGELOG.md#migration-to-v0280-beta1)
