### ISSUE TITLE
如何配置preload

### ISSUE THREAD

**Issue by spirit223** [electron-vite/vite-plugin-electron#181]
我应该如何配置插件, 让preload文件也会被编译到dist-electron中呢?
![image](https://github.com/electron-vite/vite-plugin-electron/assets/63941510/b1253bb3-c6a9-4b15-bcf6-5b434b3d075b)
我是这样使用插件的, 我不知道怎么配置preload.
我看simple可以配置preload, 但是我使用simple的配置方式不会启动electron
![image](https://github.com/electron-vite/vite-plugin-electron/assets/63941510/1cbec397-a2b2-48e0-8721-db508f4790b2)

![1699845114429](https://github.com/electron-vite/vite-plugin-electron/assets/63941510/3d170531-c9be-434e-bf3e-e54a7e56aaf6)
我的插件版本是"vite-plugin-electron": "^0.15.4", 构建工具版本"vite": "^4.4.5",

**Comment by caoxiemeihao** [comment]
https://github.com/caoxiemeihao/electron-vite-samples/tree/main/quick-start
看下样板工程

**Comment by spirit223** [comment]
我根据样板文件结构重新组织文件树, 已经解决问题了, 十分感谢

**Comment by forever-z-133** [comment]
@caoxiemeihao 版本 0.15.5 的 ts 表示不支持这样写
