### ISSUE TITLE
代码保存，页面不刷新

### ISSUE THREAD

**Issue by SanGongHappy** [electron-vite/vite-plugin-electron#184]
代码保存，页面不刷新
之前正常的，可能是用 ctrl + c 的方式关闭代码 导致
![image](https://github.com/electron-vite/vite-plugin-electron/assets/51526839/5dc362ee-ff96-49a0-b0f2-adc016dc06a4)

**Comment by SanGongHappy** [comment]
出现最下面的那句话就刷新不了了

**Comment by SanGongHappy** [comment]
重启电脑后恢复正常

**Comment by SanGongHappy** [comment]
重启过后一段时间又变不正常了，并没有进行 ctrl + c 的操作

**Comment by SanGongHappy** [comment]
使用sass 经常性，不更新，使用electron 的reload按钮依旧不实时刷新，使用vue css 样式 正常

**Comment by SanGongHappy** [comment]
> 代码保存，页面不刷新 之前正常的，可能是用 ctrl + c 的方式关闭代码 导致 ![image](https://user-images.githubusercontent.com/51526839/284493962-5dc362ee-ff96-49a0-b0f2-adc016dc06a4.png)

[10976:1121/155119.482:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)

**Comment by caoxiemeihao** [comment]
`v0.15.5` 已修复 👉 https://github.com/electron-vite/vite-plugin-electron/pull/188
