### ISSUE TITLE
存在多个preload怎么配置

### ISSUE THREAD

**Issue by badboyf** [electron-vite/vite-plugin-electron#195]
只有一个preload是这么配置的

```js
electron({
  preload: {
    // Shortcut of `build.rollupOptions.input`.
    // Preload scripts may contain Web assets, so use the `build.rollupOptions.input` instead `build.lib.entry`.
    input: 'electron/preload/index.js',
    vite: {
      build: {
        sourcemap: sourcemap ? 'inline' : undefined,
        minify: isBuild,
        outDir: 'dist-electron/preload',
        rollupOptions: {
          external: Object.keys('dependencies' in pkg ? pkg.dependencies : {}),
        },
      },
    },
  }
})
```

**Comment by caoxiemeihao** [comment]
可以使用 `input`多入口

```js
input: {
  index: 'electron/preload/index.js',
  'index-2': 'electron/preload/index-2.js',
}
```

**Comment by badboyf** [comment]
改成这样打包成功了。但是npm run dev的时候不能触发编译vue，把package.json中的scripts.dev改成 vite build && vite 后编译没问题了，又不能拉起应用，得随便找个文件触发一下文件修改的热更新才能唤起应用，是配置不对，还是bug？
`     preload: {
          input: {    // 修改点 
            index: 'electron/preload/index.js',
            index2: 'electron/preload/preload2.js'
          },
          vite: {
            build: {
              minify: isBuild,
              outDir: 'dist-electron/preload',
              rollupOptions: {
                output:{    // 修改点 
                  inlineDynamicImports: false
                },
                external: Object.keys('dependencies' in pkg ? pkg.dependencies : {}),
              },
            },
          },
        },
`

**Comment by badboyf** [comment]
preload: {
          // Shortcut of `build.rollupOptions.input`.
          // Preload scripts may contain Web assets, so use the `build.rollupOptions.input` instead `build.lib.entry`.
          input: {
            index: 'electron/preload/index.js',
            index2: 'electron/preload/preload2.js',
            index3: 'electron/preload/preload3.js'
          },
          vite: {
            build: {
              // sourcemap: sourcemap ? 'inline' : undefined, // #332
              minify: isBuild,
              outDir: 'dist-electron/preload',
              rollupOptions: {
                output:{
                  inlineDynamicImports: false
                },
                external: Object.keys('dependencies' in pkg ? pkg.dependencies : {}),
              },
            },
          },
        }

**Comment by badboyf** [comment]
实验了下，只要input 下配置了多个入口，npm run dev的时候就不能唤起应用

**Comment by badboyf** [comment]
除了main、preload文件夹怎么配置编译

**Comment by caoxiemeihao** [comment]
你改成拉平得配置，可以无限制配置 preload 数量。
https://github.com/electron-vite/electron-vite-vue/blob/85ed267c4851bf59f32888d766c0071661d4b94c/vite.config.flat.txt#L19-L66

---

直接配置 `preload: { input: ['1.ts', '2.ts'] }`   这种配置，如果出现了公共引用 Rollup 会强制 chunks 且依赖主进程开启 node.js
