### ISSUE TITLE
The preload.ts in the electron-vite-react template file is not running

### ISSUE THREAD

**Issue by yinvoke** [electron-vite/vite-plugin-electron#207]
![image](https://github.com/electron-vite/vite-plugin-electron/assets/41604578/73427eaf-a9e9-4315-80d3-e14670e3baf5)

Install using the method provided on the official website  （https://electron-vite.github.io/guide/getting-started.html）
npm create electro-vite@latest 

but preload.ts not run :(

**Comment by Igloczek** [comment]
Do you have it loaded in your `electron/main.ts` like this https://github.com/caoxiemeihao/electron-vite-samples/blob/main/quick-start/electron/main.ts#L29-L31 ?
