### ISSUE TITLE
怎么确保打包后的app.asar文件的安全性？

### ISSUE THREAD

**Issue by yaoshengli** [electron-vite/vite-plugin-electron#213]
asar文件反编译后很容易看到源码，有什么好的加密办法吗~

**Comment by yaoshengli** [comment]
https://github.com/alex8088/electron-vite 这里有个v8字节保护，奈何自己没文化，想问作者我们的插件可以内置进去吗~~撒花

**Comment by yaoshengli** [comment]
原来可以直接用electron-vite的bytecodePlugin插件  只需设置process.env.NODE_ENV_ELECTRON_VITE='production'即可~  搞定~

**Comment by yaoshengli** [comment]
然后就可以看文档使用了~

**Comment by vabaly** [comment]
> ```ts
> process.env.NODE_ENV_ELECTRON_VITE = 'production' 
> ```

请问这个问题解决了吗？

**Comment by zhimingzhang123** [comment]
> > ```ts
> > process.env.NODE_ENV_ELECTRON_VITE = 'production' > 
> > ```
> 
> @zhimingzhang123 请问这个问题解决了吗？

@vabaly 将`process.env.NODE_ENV_ELECTRON_VITE = 'production' ` 这段代码放在`vite.config.ts`这个文件中。
