### ISSUE TITLE
App.asar doesn't have dist folder when build is finished

### ISSUE THREAD

**Issue by AMV1909** [electron-vite/vite-plugin-electron#215]
I've created a new project of electron-vite to prove it and tried to build it (I didn't modifies anything on the code), but when build is finished and run the program, I get an error in the console telling me that the program isn't finding the index.html

I've verified the content of the App.asar file and I realize that there isn't dist folder inside of it
![Captura](https://github.com/alex8088/electron-vite/assets/78486180/c0486d1e-402d-4bd9-9067-d80c9b679cfd)
![image](https://github.com/alex8088/electron-vite/assets/78486180/d9754070-5d02-4f8d-81a9-bf21378f73e6)

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?
