### ISSUE TITLE
Please update for electron version 29.1.1

### ISSUE THREAD

**Issue by crystalfp** [electron-vite/vite-plugin-electron#221]
Installing any package elicit a version problem with `vite-plugin-electron` v0.28.2
This plugin expects `electron` version 28. Instead I have version 29.1.1 installed.
Could the plugin be updated to this electron version?
Thanks!
mario

**Comment by caoxiemeihao** [comment]
This plugin does not rely on the version of the electron, there are electron@29 A prototype project.
This plugin does not rely on the version of the electron, there are electron@29 example 👉 https://github.com/electron-vite/electron-vite-react
