### ISSUE TITLE
Access to Node API

### ISSUE THREAD

**Issue by NicoLaval** [electron-vite/vite-plugin-electron#227]
In a CRA + Electron project I was doing

```ts
const { readdirSync, statSync, accessSync, constants } = window.require('node:fs')
```

How to access to these functions with `electron-vite`?

**Comment by caoxiemeihao** [comment]
Please refer to the official documentation of Electron on using the Node.js API during the rendering process.
https://www.electronjs.org/docs/latest/api/structures/web-preferences

<img width="740" alt="image" src="https://github.com/electron-vite/vite-plugin-electron/assets/26263658/f3712912-2d3c-4850-9884-19f5ddecda47">
