### ISSUE TITLE
0.28.6 error: Could not dynamically require "url"

### ISSUE THREAD

**Issue by tadmi** [electron-vite/vite-plugin-electron#234]
After updating 0.28.5 > 0.28.6, I get an error:

App threw an error during load
Error: Could not dynamically require "url". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?

**Comment by tadmi** [comment]
I'm sorry, the problem is in my project: for some reason, asciidoctor.js is loaded as commonjs instead of esm.
