### ISSUE TITLE
ESM包使用出现的问题

### ISSUE THREAD

**Issue by LonelyFellas** [electron-vite/vite-plugin-electron#239]
```js
import ffi from 'ffi-napi';
export function test() {
  console.log('test', ffi);
  return 111;
}
```
ERR: 
```log
App threw an error during load
ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and 'D:\Dev\maiku\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///D:/Dev/maiku/dist-electron/main.js:16394:61
    at file:///D:/Dev/maiku/dist-electron/main.js:16944:3
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadApplicationPackage (file:///D:/Dev/maiku/node_modules/electron/dist/resources/default_app.asar/main.js:129:9)
    at async file:///D:/Dev/maiku/node_modules/electron/dist/resources/default_app.asar/main.js:241:9
```
我知道`ffi-napi`是c++模块中的commonjs模块的js包，我怎么能正常使用，请大家给我点建议

**Comment by leiyaguang** [comment]
一样的问题

**Comment by subframe7536** [comment]
`__dirname` 只在 commonjs 中生效

删除 D:\Dev\maiku\package.json 的 "type": "module"

**Comment by LonelyFellas** [comment]
> `__dirname` 只在 commonjs 中生效
> 
> 删除 D:\Dev\maiku\package.json 的 "type": "module"

默认的配置本身就是type：module，你这样其他地方需要改的地方很多。

**Comment by LonelyFellas** [comment]
> 一样的问题

我是就ffi-napi 更换成了 koffi 这个库。koffi是支持esm的， 如果你要导入commonjs的包可以尝试这样
```import { createRequire } from 'node:module';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const cwp = require('captures-win-position/lib/main.js');```

**Comment by subframe7536** [comment]
没办法，总有一个地方要改

**Comment by LonelyFellas** [comment]
> 没办法，总有一个地方要改

没事我找到了一个平替

**Comment by LonelyFellas** [comment]
@subframe7536 其实还有一个办法，就是将这个库另外用rollup打包成esm，然后呢修改部分打包后的源代码，比如__dirname 可能还要进行特别的修改 ` const __dirname =   path.dirname(fileURLToPath(import.meta.url));` 就好了，能正常使用

**Comment by LonelyFellas** [comment]
@subframe7536 你觉得这个方案行不行

**Comment by subframe7536** [comment]
也是一种思路，但是最好封装成一个插件，每次有改动不需要手动修改源码

当然了，如果打包完就不动了就无所谓

**Comment by LonelyFellas** [comment]
是的！打包后对源码再执行一些写脚本就行了。把这一些东西替换上去

**Comment by swift-fs** [comment]
> > 一样的问题
> 
> 我是就ffi-napi 更换成了 koffi 这个库。koffi是支持esm的， 如果你要导入commonjs的包可以尝试这样
> 
> ```
> import { createRequire } from 'node:module';
> const require = createRequire(import.meta.url);
> const cwp = require('captures-win-position/lib/main.js');```
> ```
这个方法非常好用~~

**Comment by kingyue737** [comment]
> 也是一种思路，但是最好封装成一个插件，每次有改动不需要手动修改源码
> 
> 当然了，如果打包完就不动了就无所谓

有现成的rollup官方插件的[@rollup/plugin-esm-shim](https://www.npmjs.com/package/@rollup/plugin-esm-shim)。我的所有electron应用都是ESM，没用过CJS，暂时没有遇到问题。
