### ISSUE TITLE
How do I import other ts files in version 0.28 /electron/main/index.ts | 如何在0.28版本  /electron/main/index.ts 中引入其他ts文件

### ISSUE THREAD

**Issue by SanGongHappy** [electron-vite/vite-plugin-electron#240]
I use the following code in vite.config.ts, which causes my ts file to generate mjs files, but my other ts files in the folder do not generate mjs files   |    我在vite.config.ts 中使用如下代码，会使我的ts文件会生成mjs文件，但是我在文件夹中的其他ts文件不生成mjs文件

```

import fs from "node:fs";
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import path from "path";
import pkg from "./package.json";
import electron from "vite-plugin-electron";
import renderer from "vite-plugin-electron-renderer";

import { loadEnv } from "vite";
import { fileURLToPath } from "node:url";

// 按需导入
// import AutoImport from 'unplugin-auto-import/vite'

// https://vitejs.dev/config/
export default defineConfig(({ command }) => {
  fs.rmSync("dist-electron", { recursive: true, force: true });

  const isServe = command === "serve";
  const isBuild = command === "build";
  const sourcemap = isServe || !!process.env.VSCODE_DEBUG;

  return {
    base: "./",
    plugins: [
      vue(),
      electron([
        {
          entry: "electron/main/index.ts",
          onstart(options) {
            if (process.env.VSCODE_DEBUG) {
              /* eslint-disable no-console */
              console.log("[startup] Electron App");
            } else {
              options.startup();
            }
          },

          vite: {
            build: {
              outDir: "dist-electron/main",
              rollupOptions: {
                external: Object.keys(
                  "dependencies" in pkg ? pkg.dependencies : {},
                ),
                output: {
                  format: "esm",
                  entryFileNames: `[name].mjs`,
                },
              },
            },
          },
        },

        {
          entry: "electron/preload/index.ts",
          onstart(options) {
            options.reload();
          },
          vite: {
            build: {
              outDir: "dist-electron/preload",
              rollupOptions: {
                external: Object.keys(
                  "dependencies" in pkg ? pkg.dependencies : {},
                ),
                output: {
                  format: "esm",
                  entryFileNames: `[name].mjs`,
                },
              },
            },
          },
        },
      ]),
      renderer({
        resolve: {
          serialport: { type: "cjs" },
          got: { type: "esm" },
        },
      }),
    ],
  };
});


```

**Comment by yejimeiming** [comment]
`entry` 支持多文件入口，参考 Vite 文档 👉🏻 https://vitejs.dev/guide/build.html#library-mode

**Comment by SanGongHappy** [comment]
有没有方式，批量转换 ts 文件到 mjs，因为开发者对mjs实际上是不需要的，应该专注于ts文件的逻辑，且一但文件多了以后，这种方式会很麻烦

**Comment by yejimeiming** [comment]
你可能直接使用 `esbuild` 或者 `tsc` 更合适，Vite 是个 bundler 不是 transformer

**Comment by SanGongHappy** [comment]
`import fs from "node:fs";
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import path from "path";
import pkg from "./package.json";
import electron from "vite-plugin-electron";
import renderer from "vite-plugin-electron-renderer";

import { loadEnv } from "vite";
import { fileURLToPath } from "node:url";

// 按需导入
// import AutoImport from 'unplugin-auto-import/vite'

// 检索路径中所有.ts文件
function getTsFiles(directory) {
  const result = [];

  // 读取目录内容
  const files = fs.readdirSync(directory);

  // 遍历每个文件
  files.forEach((file) => {
    const filePath = path.join(directory, file);

    // 获取文件信息
    const stat = fs.statSync(filePath);

    // 如果是文件夹，则递归查找
    if (stat.isDirectory()) {
      result.push(...getTsFiles(filePath)); // 递归调用
    } else if (file.endsWith(".ts")) {
      result.push(filePath.replace(/\\/g, "/")); // 如果是.ts文件，加入结果数组
    }
  });

  return result;
}
// 获取所有渲染进程文件
function getRendererPages(electronPages) {
  let rendererPages = [];
  electronPages.forEach((page) => {
    // 找到第一个斜杠的位置
    const firstSlashIndex = page.indexOf("/");
    // 找到最后一个斜杠的位置
    const lastSlashIndex = page.lastIndexOf("/");
    // 判断路径中是否存在多个斜杠
    let result = page;
    // 如果路径中有斜杠，进行处理
    if (
      firstSlashIndex !== -1 &&
      lastSlashIndex !== -1 &&
      firstSlashIndex !== lastSlashIndex
    ) {
      // 截取第一个斜杠后和最后一个斜杠前的部分
      result = page.slice(firstSlashIndex + 1, lastSlashIndex);
    } else {
      // 如果只有一个斜杠或没有斜杠，返回空字符串
      result = "";
    }

    let outDir = "dist-electron/" + result;
    console.log(outDir);

    rendererPages.push({
      entry: page,
      onstart(options) {
        if (process.env.VSCODE_DEBUG) {
          console.log("[startup] Electron App");
        } else {
          options.startup();
        }
      },

      vite: {
        build: {
          outDir: outDir,
          rollupOptions: {
            external: Object.keys(
              "dependencies" in pkg ? pkg.dependencies : {}
            ),
            output: {
              format: "esm",
              entryFileNames: `[name].mjs`,
            },
          },
        },
      },
    });
  });
  return rendererPages;
}

// https://vitejs.dev/config/
export default defineConfig(({ command }) => {
  fs.rmSync("dist-electron", { recursive: true, force: true });

  const isServe = command === "serve";
  const isBuild = command === "build";
  const sourcemap = isServe || !!process.env.VSCODE_DEBUG;

  let electronPages = getTsFiles("./electron");

  let rendererPages = getRendererPages(electronPages);

  return {
    base: "./",
    plugins: [
      vue(),
      electron(rendererPages),
      renderer({
        resolve: {
          serialport: { type: "cjs" },
          got: { type: "esm" },
        },
      }),
    ],
  };
});
`
我修改成了这样，windows测试是OK的，感觉这样会方便很多，我希望能加入示例中

**Comment by SanGongHappy** [comment]
`
import fs from "node:fs";
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import path from "path";
import pkg from "./package.json";
import electron from "vite-plugin-electron";
import renderer from "vite-plugin-electron-renderer";

import { loadEnv } from "vite";
import { fileURLToPath } from "node:url";

// 按需导入
// import AutoImport from 'unplugin-auto-import/vite'

// 检索路径中所有.ts文件
function getTsFiles(directory) {
  const result = [];

  // 读取目录内容
  const files = fs.readdirSync(directory);

  // 遍历每个文件
  files.forEach((file) => {
    const filePath = path.join(directory, file);

    // 获取文件信息
    const stat = fs.statSync(filePath);

    // 如果是文件夹，则递归查找
    if (stat.isDirectory()) {
      result.push(...getTsFiles(filePath)); // 递归调用
    } else if (file.endsWith(".ts")) {
      result.push(filePath.replace(/\\/g, "/")); // 如果是.ts文件，加入结果数组
    }
  });

  return result;
}
// 获取所有渲染进程文件
function getRendererPages(electronPages) {
  let rendererPages = [];
  electronPages.forEach((page) => {
    // 找到第一个斜杠的位置
    const firstSlashIndex = page.indexOf("/");
    // 找到最后一个斜杠的位置
    const lastSlashIndex = page.lastIndexOf("/");
    // 判断路径中是否存在多个斜杠
    let result = page;
    // 如果路径中有斜杠，进行处理
    if (
      firstSlashIndex !== -1 &&
      lastSlashIndex !== -1 &&
      firstSlashIndex !== lastSlashIndex
    ) {
      // 截取第一个斜杠后和最后一个斜杠前的部分
      result = page.slice(firstSlashIndex + 1, lastSlashIndex);
    } else {
      // 如果只有一个斜杠或没有斜杠，返回空字符串
      result = "";
    }

    let outDir = "dist-electron/" + result;
    console.log(outDir);

    rendererPages.push({
      entry: page,
      onstart(options) {
        if (process.env.VSCODE_DEBUG) {
          console.log("[startup] Electron App");
        } else {
          options.startup();
        }
      },

      vite: {
        build: {
          outDir: outDir,
          rollupOptions: {
            external: Object.keys(
              "dependencies" in pkg ? pkg.dependencies : {}
            ),
            output: {
              format: "esm",
              entryFileNames: "[name].mjs",
            },
          },
        },
      },
    });
  });
  return rendererPages;
}

// https://vitejs.dev/config/
export default defineConfig(({ command }) => {
  fs.rmSync("dist-electron", { recursive: true, force: true });

  const isServe = command === "serve";
  const isBuild = command === "build";
  const sourcemap = isServe || !!process.env.VSCODE_DEBUG;

  let electronPages = getTsFiles("./electron");

  let rendererPages = getRendererPages(electronPages);

  return {
    base: "./",
    plugins: [
      vue(),
      electron(rendererPages),
      renderer({
        resolve: {
          serialport: { type: "cjs" },
          got: { type: "esm" },
        },
      }),
    ],
  };
});

`

我这样增加了批量引入，windows下测试正常，这样我个人感觉很方便，如果感觉可以的话，我去示例中加一下这个

**Comment by SanGongHappy** [comment]
import fs from "node:fs";
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import path from "path";
import pkg from "./package.json";
import electron from "vite-plugin-electron";
import renderer from "vite-plugin-electron-renderer";

import { loadEnv } from "vite";
import { fileURLToPath } from "node:url";

// 按需导入
// import AutoImport from 'unplugin-auto-import/vite'

// 检索路径中所有.ts文件
function getTsFiles(directory) {
  const result = [];

  // 读取目录内容
  const files = fs.readdirSync(directory);

  // 遍历每个文件
  files.forEach((file) => {
    const filePath = path.join(directory, file);

    // 获取文件信息
    const stat = fs.statSync(filePath);

    // 如果是文件夹，则递归查找
    if (stat.isDirectory()) {
      result.push(...getTsFiles(filePath)); // 递归调用
    } else if (file.endsWith(".ts")) {
      result.push(filePath.replace(/\\/g, "/")); // 如果是.ts文件，加入结果数组
    }
  });

  return result;
}
// 获取所有渲染进程文件
function getRendererPages(electronPages) {
  let rendererPages = [];
  electronPages.forEach((page) => {
    // 找到第一个斜杠的位置
    const firstSlashIndex = page.indexOf("/");
    // 找到最后一个斜杠的位置
    const lastSlashIndex = page.lastIndexOf("/");
    // 判断路径中是否存在多个斜杠
    let result = page;
    // 如果路径中有斜杠，进行处理
    if (
      firstSlashIndex !== -1 &&
      lastSlashIndex !== -1 &&
      firstSlashIndex !== lastSlashIndex
    ) {
      // 截取第一个斜杠后和最后一个斜杠前的部分
      result = page.slice(firstSlashIndex + 1, lastSlashIndex);
    } else {
      // 如果只有一个斜杠或没有斜杠，返回空字符串
      result = "";
    }

    let outDir = "dist-electron/" + result;
    console.log(outDir);

    rendererPages.push({
      entry: page,
      onstart(options) {
        if (process.env.VSCODE_DEBUG) {
          console.log("[startup] Electron App");
        } else {
          options.startup();
        }
      },

      vite: {
        build: {
          outDir: outDir,
          rollupOptions: {
            external: Object.keys(
              "dependencies" in pkg ? pkg.dependencies : {}
            ),
            output: {
              format: "esm",
              entryFileNames: "[name].mjs",
            },
          },
        },
      },
    });
  });
  return rendererPages;
}

// https://vitejs.dev/config/
export default defineConfig(({ command }) => {
  fs.rmSync("dist-electron", { recursive: true, force: true });

  const isServe = command === "serve";
  const isBuild = command === "build";
  const sourcemap = isServe || !!process.env.VSCODE_DEBUG;

  let electronPages = getTsFiles("./electron");

  let rendererPages = getRendererPages(electronPages);

  return {
    base: "./",
    plugins: [
      vue(),
      electron(rendererPages),
      renderer({
        resolve: {
          serialport: { type: "cjs" },
          got: { type: "esm" },
        },
      }),
    ],
});

我在windows上使用这个代码，批量转换了ts到mjs，我感觉这样改下来会方便很多，可以的话，我去示例中提交这串代码

**Comment by SanGongHappy** [comment]
**import fs from "node:fs";
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import path from "path";
import pkg from "./package.json";
import electron from "vite-plugin-electron";
import renderer from "vite-plugin-electron-renderer";

import { loadEnv } from "vite";
import { fileURLToPath } from "node:url";

// 按需导入
// import AutoImport from 'unplugin-auto-import/vite'

// 检索路径中所有.ts文件
function getTsFiles(directory) {
const result = [];

// 读取目录内容
const files = fs.readdirSync(directory);

// 遍历每个文件
files.forEach((file) => {
const filePath = path.join(directory, file);

// 获取文件信息
const stat = fs.statSync(filePath);

// 如果是文件夹，则递归查找
if (stat.isDirectory()) {
  result.push(...getTsFiles(filePath)); // 递归调用
} else if (file.endsWith(".ts")) {
  result.push(filePath.replace(/\\/g, "/")); // 如果是.ts文件，加入结果数组
}
});

return result;
}
// 获取所有渲染进程文件
function getRendererPages(electronPages) {
let rendererPages = [];
electronPages.forEach((page) => {
// 找到第一个斜杠的位置
const firstSlashIndex = page.indexOf("/");
// 找到最后一个斜杠的位置
const lastSlashIndex = page.lastIndexOf("/");
// 判断路径中是否存在多个斜杠
let result = page;
// 如果路径中有斜杠，进行处理
if (
firstSlashIndex !== -1 &&
lastSlashIndex !== -1 &&
firstSlashIndex !== lastSlashIndex
) {
// 截取第一个斜杠后和最后一个斜杠前的部分
result = page.slice(firstSlashIndex + 1, lastSlashIndex);
} else {
// 如果只有一个斜杠或没有斜杠，返回空字符串
result = "";
}

let outDir = "dist-electron/" + result;
console.log(outDir);

rendererPages.push({
  entry: page,
  onstart(options) {
    if (process.env.VSCODE_DEBUG) {
      console.log("[startup] Electron App");
    } else {
      options.startup();
    }
  },

  vite: {
    build: {
      outDir: outDir,
      rollupOptions: {
        external: Object.keys(
          "dependencies" in pkg ? pkg.dependencies : {}
        ),
        output: {
          format: "esm",
          entryFileNames: "[name].mjs",
        },
      },
    },
  },
});
});
return rendererPages;
}

// https://vitejs.dev/config/
export default defineConfig(({ command }) => {
fs.rmSync("dist-electron", { recursive: true, force: true });

const isServe = command === "serve";
const isBuild = command === "build";
const sourcemap = isServe || !!process.env.VSCODE_DEBUG;

let electronPages = getTsFiles("./electron");

let rendererPages = getRendererPages(electronPages);

return {
base: "./",
plugins: [
vue(),
electron(rendererPages),
renderer({
resolve: {
serialport: { type: "cjs" },
got: { type: "esm" },
},
}),
],
});**

我在windows上使用这个代码，批量转换了ts到mjs，我感觉这样改下来会方便很多，可以的话，我去示例中提交这串代码
