### ISSUE TITLE
How to import static resources in the Main process and keep them as URLs?

### ISSUE THREAD

**Issue by oubenruing** [electron-vite/vite-plugin-electron#241]
As shown in the code below

``` typescript

import { app, Menu, nativeImage, Tray } from 'electron'
import icon from '../../assets/logo.png'

console.log(icon)
// data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAA.....
const tray = new Tray(nativeImage.createFromPath(icon))


```
I used Vite's import to import an image, but after the build, it gets packaged as a base64 string. I want to keep it as a URL. What should I do? Also, I added assetsInlineLimit: 0 in the Electron plugin, but it didn't work.

``` diff
export default defineConfig(({ command }) => {
  return {
    plugins: [
      // ...
      electron({
        main: {
          // Shortcut of `build.lib.entry`
          entry: 'electron/main/index.ts',
          onstart({ startup }) {
            if (process.env.VSCODE_DEBUG) {
              console.log(/* For `.vscode/.debug.script.mjs` */ '[startup] Electron App')
            } else {
              startup()
            }
          },
          vite: {
            build: {
              sourcemap,
              minify: isBuild,
              outDir: 'dist-electron/main',
+             assetsInlineLimit: 0,
              rollupOptions: {
                // Some third-party Node.js libraries may not be built correctly by Vite, especially `C/C++` addons,
                // we can use `external` to exclude them to ensure they work correctly.
                // Others need to put them in `dependencies` to ensure they are collected into `app.asar` after the app is built.
                // Of course, this is not absolute, just this way is relatively simple. :)
                // output: { format: 'es' },
                external: Object.keys('dependencies' in pkg ? pkg.dependencies : {})
              }
            }
          }
        },
      }
//...
```
It can be reproduced [https://github.com/oubenruing/test-electron](https://github.com/oubenruing/test-electron)

**Comment by yejimeiming** [comment]
See this doc 👉🏻 https://vitejs.dev/guide/assets.html#importing-asset-as-string

**Comment by oubenruing** [comment]
> See this doc 👉🏻 https://vitejs.dev/guide/assets.html#importing-asset-as-string

Thank you for your response.

 I have carefully read the Vite documentation and tried modifying the configuration and import syntax, but this didn't solve my issue. 

In Electron, I imported the same image in both the main process and the renderer process. 

1. In the main process, a JS file was generated with the image converted to a base64 string and embedded in the file. 
2. In the renderer process, the image was placed in the assets folder, and the generated JS referenced the image using new URL('xxx.png', import.meta.url).href. 

I would like the JS file generated in the main process to also reference the image using the new URL method, but I'm not sure how to achieve this.

**Comment by yejimeiming** [comment]
By default `vite-plugin-electron` uses `build.lib` to build the Main process, which seems to always build **image** resources as **base64**
If we use the `build.rollupOptions.input` option, the image will output a normal path normally.

```diff
import { defineConfig } from 'vite'
import electron from 'vite-plugin-electron/simple'

export default defineConfig({
  plugins: [
    electron({
      main: {
-       entry: 'electron/main/index.ts',
+        vite: {
+          build: {
+            rollupOptions: {
+              input: 'electron/main.ts',
+              output: {
+                format: 'cjs',
+
+                // Same behavior as `build.lib`.
+                inlineDynamicImports: true,
+                entryFileNames: '[name].js',
+                chunkFileNames: '[name].js',
+                assetFileNames: '[name].[ext]',
+              },
+            },
+          },
+        },
      },
      preload: {
        input: 'electron/preload.ts',
      },
    }),
  ],
})
```

---

Vite source code 👉🏻 https://github.com/vitejs/vite/blob/main/packages/vite/src/node/plugins/asset.ts#L428

**Comment by yejimeiming** [comment]
Of course, I suggest you create a **static** folder to store image resources. At the same time, you need to configure `static` to the `files` option of `electron-builder.json5`, so that when the App is built, the **static** folder will be copied to `app.asar`.
In this way, you can access them through `fs.readFile('../static/xxx.png')` in the main process.

**Comment by oubenruing** [comment]
Awesome! It worked for me. Thanks again!
