### ISSUE TITLE
增加electron之后，打包报错      `[vite:build-import-analysis] 

### ISSUE THREAD

**Issue by hunniman** [electron-vite/vite-plugin-electron#254]
原有vite+vue3项目，加入electron之后：
vite.config.js:
```

  plugins: [
      vue(),
      electron({
        main: {
          entry: 'electron/main.js'
          // preload: 'preload.cjs'
        },
        preload: {
          // Shortcut of `build.rollupOptions.input`
          input: 'electron/preload.cjs'
        },
        // Optional: Use Node.js API in the Renderer process
        renderer: {},
      }),
  
    ],
```
报错：
 [vite:build-import-analysis] [plugin vite:build-import-analysis] src/App.vue (5:8): Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.
file: E:/WebProject/vite_demo01/src/App.vue:5:8

环境：
node 20 
```

  "devDependencies": {
    "@vitejs/plugin-vue": "^5.1.4",
    "electron": "^32.1.2",
    "electron-builder": "^25.0.5",
    "vite": "^5.3.1",
    "vite-plugin-electron": "^0.28.8",
    "vite-plugin-electron-renderer": "^0.14.6",
    "vite-plugin-mock": "^3.0.2"
  }
```
  
  求教

**Comment by yejimeiming** [comment]
和 vite-plugin-electron 没关系，你的 App.vue 文件里面 import 写法问题。看下 Vite 官方文档对 import 要求
https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations
