### ISSUE TITLE
请求：默认的应用输出能不能弄成带菜单的？

### ISSUE THREAD

**Issue by hunteryun** [electron-vite/vite-plugin-electron#3]
呃。主要是光秃秃的，在继承开发时，如果有问题就什么也看不到错误提示，能不能弄个菜单，至少让人可以打开开发工具查看错误？

呃，糟糕，发错位置了，应该是：https://github.com/caoxiemeihao/vite-plugin-electron-quick-start

**Comment by caoxiemeihao** [comment]
欢迎 PR
