### ISSUE TITLE
ThreeJS is used in the project, and the interface cannot be displayed after packaging.

### ISSUE THREAD

**Issue by robomentor** [electron-vite/vite-plugin-electron#31]
**ThreeJS is used in the project, and the interface cannot be displayed after packaging.**

lingo3D is a 3D development framework based on ThreeJS package

project address: https://github.com/robomentor/Electron_Threejs_Template

The development environment can be used normally, but the interface cannot be displayed after packaging, and there is no related error message.

How to use:

yarn && yarn electron:rebuild

development mode：yarn electron:dev

release mode：yarn electron:build && yarn electron:win64
or
release mode：yarn electron:build && yarn electron:win32
or
release mode：yarn electron:build && yarn electron:mac

**Comment by robomentor** [comment]
@magicdawn @ZiGmaX809 @youngleish @SharerMax

**Comment by caoxiemeihao** [comment]
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/26263658/178394399-7800f781-0041-4d4d-8e0d-cece28a2e20a.png">

**Comment by robomentor** [comment]
Install node-gyp as administrator：yarn add -g node-gyp@7.1.0

**Comment by robomentor** [comment]
I just submitted an update, you can redownload the code, no need: yarn electron:rebuild

**Comment by caoxiemeihao** [comment]
没法帮你，应用打包贼慢不知道为啥，打包后打开贼卡；从打包到能点击应用十分钟过去了，打开等十分钟蹦出来个控制台失去链接。太耗时间了，你去看下 `lingo3d-vue` 的源码吧

**Comment by robomentor** [comment]
国产的？我以为是国外团队维护的呢，打包慢可能是因为打包所需的东西下载慢，你可以设置下代理：
```
registry "https://registry.npm.taobao.org/"
electron_mirror "https://npm.taobao.org/mirrors/electron/"
electron_builder_binaries_mirror "http://npm.taobao.org/mirrors/electron-builder-binaries/"
```
应该不是lingo3d-vue的问题，之前没使用vite-plugin-electron可以顺利打包，帮忙再排查下呗。

**Comment by caoxiemeihao** [comment]
你要么试下 https://github.com/electron-vite/electron-vite-boilerplate 这个模板吧，这个还保留最原始的样子
代理配了没用，构建后打开就白屏；卡好久

**Comment by robomentor** [comment]
现在的问题就是打包后白屏，啥也不显示

**Comment by robomentor** [comment]
> 

这个模板我尝试过了，也一样的问题。

**Comment by robomentor** [comment]
> 你要么试下 https://github.com/electron-vite/electron-vite-boilerplate 这个模板吧，这个还保留最原始的样子 代理配过了，构建还是慢；问题是构建后打开就白屏；卡好久，查不动

这个模板我测试一下，之前测试的不是这个。

**Comment by caoxiemeihao** [comment]
试下新插件 https://github.com/electron-vite/vite-electron-plugin 能无缝兼容各种 Node.js 情况
