### ISSUE TITLE
How can I call the browser.close() function of playwright every time in development mode ?

### ISSUE THREAD

**Issue by parapada73** [electron-vite/vite-plugin-electron#34]
The electronic application I made runs **playwright**. The **browser.close()** function must be called to exit playwright.

How can I call the browser.close() function of playwright every time in development mode (npm run dev)?

**Comment by caoxiemeihao** [comment]
What timing are you referring to? HRM or Electron APP restart?

**Comment by parapada73** [comment]
> What timing are you referring to? HRM or Electron APP restart?

I think electron application restart is correct.

Whenever I modify the electronic code, the electronic application runs again. I want to know how to run the browser.close() function of playwright just before the electron application runs again.

**Comment by caoxiemeihao** [comment]
You can write a minisize plugin, then put logic of  `browser.close()` in `writeBundle()` hooks.  
`browser.close()` will be run at Electron APP restart an every time.  

> The below code snippet is  restart logic for Electron APP

https://github.com/electron-vite/electron-vite-boilerplate/blob/a32daabb84a9b4210f45334d0eeedccb8b76c66f/scripts/watch.mjs#L18-L28

```ts
plugins: [{
  name: 'electron-main-watcher',
  writeBundle() {
    if (process.electronApp) {
      process.electronApp.removeAllListeners()
      process.electronApp.kill()
    }
    process.electronApp = spawn(electron, ['.'], { stdio: 'inherit', env })
    process.electronApp.once('exit', process.exit)
  },
}],
```
