### ISSUE TITLE
vite3

### ISSUE THREAD

**Issue by feiyuhao** [electron-vite/vite-plugin-electron#35]
感谢您的插件，请问有计划支持vite3吗？

**Comment by caoxiemeihao** [comment]
> 感谢您的插件，请问有计划支持vite3吗？

肯定有计划啊，这个插件本来就是和 Vite3 兼容的；[electron-vite-vue](https://github.com/electron-vite/electron-vite-vue) 上个礼拜试了下 Vite3 结果碰到了一些 BUG.  
稍微回归下测试下，没啥问题会从 electron-vite-vue 组织下的模板开始试水

**Comment by Hunlongyu** [comment]
哈喽，几天过去了，试了几次，目前插件好像不能正常工作，是我代码有问题，还是插件目前没有兼容 vite3 吗？

**Comment by caoxiemeihao** [comment]
Vite3 目前还不咋稳定，构建后代码貌似有点小 BUG，有人在提 issue。
我这两天在重构插件的新版本，也刚好打算试试 Vite3。

**Comment by Hunlongyu** [comment]
我刚刚 参考 electron-vite-vue 修修改改，项目竟然跑起来了。不得不说，确实快啊，比公司的老项目快了好几分钟，比我自己用的 vue/cli 的那个也快了很多。vite yyds
