### ISSUE TITLE
.env variables missing from build

### ISSUE THREAD

**Issue by stefnotch** [electron-vite/vite-plugin-electron#37]
**Steps to reproduce**
1. Create a `.env` file with `VITE_CAT=meow`
2. Go to `electron/main.index.ts` and add `console.log(import.meta.env.VITE_CAT);`
3. Run `npm run dev` and look at the output in the terminal. 

**Bug**
It will say `undefined`

**Expected**
It should say `meow`

The issue is here, this line should probably be deleted
https://github.com/electron-vite/vite-plugin-electron/blob/841cbd1041ca4246b3ca6b5aea0ccfa7da969eae/packages/electron/src/config.ts#L32

**Comment by caoxiemeihao** [comment]
Thanks for your feedback. At present, Vite cann't be handled `process.env.XXX`. May be supported in the near future.
https://github.com/vitejs/vite/pull/8843

**Comment by stefnotch** [comment]
True, being able to use `process.env.` environment variables in the main-process would be much neater.

Any idea how I should work around `process.env.VITE_CAT` or `import.meta.env.VITE_CAT` not working at all? Especially for a build, I'd like to have them replaced with the contents of the `.env` file.

Currently I'm using such `.env` variables to set the URL of a server that the Electron app needs. Should I just hardcode the URL for now?

**Comment by stefnotch** [comment]
I found a workaround that I'll try using https://github.com/ElMassimo/vite-plugin-environment#inside-the-box-

**Comment by caoxiemeihao** [comment]
Support envFile options https://github.com/electron-vite/vite-plugin-electron/pull/46
