### ISSUE TITLE
请问如何构建多窗口

### ISSUE THREAD

**Issue by Hunlongyu** [electron-vite/vite-plugin-electron#39]
项目地址：https://github.com/Hunlongyu/processing/blob/main/vite.config.ts
开发的时候能够正常打开多窗口，但构建的时候，会报错，提示找不到对应的 js 文件。

开发模式：
![image](https://user-images.githubusercontent.com/15273630/180206821-e8ae5a1f-2356-452d-8490-68adc55d0e61.png)

生产模式：
![image](https://user-images.githubusercontent.com/15273630/180206761-6bd60e22-b5a1-4153-b1b5-66b0af2af91e.png)

大佬能帮忙看一下吗？

**Comment by caoxiemeihao** [comment]
把 `pages` 中的 html 拿出来放到和 `index.html` 平级即可，默认 Vite 只支持平级。

**Comment by Hunlongyu** [comment]
感谢，这样做确实解决了构建问题。
![image](https://user-images.githubusercontent.com/15273630/180595736-4f70d288-e93c-436c-ac89-59334f64ed18.png)
不过有更好的解决方案吗？比如像之前那样，把 html 放到一个统一的 pages 文件夹下？因为如果我有十几个多窗口，那根目录下就有十几个 html 。看起来很难受。

你说默认 vite 只支持平级，那言外之意是有配置项，可以配置，还是说可以通过其他第三方插件可以解决这个问题吗？

**Comment by caoxiemeihao** [comment]
可以通过第三方插件解决 `vite-html-plugin`，插件周一上线。

**Comment by Hunlongyu** [comment]
话说 这个 vite-plugin-electron.log 可以通过配置关闭吗？有时候只是启动项目，但并没有修改代码，也会导致有 git 未提交的提示。

**Comment by caoxiemeihao** [comment]
> 话说 这个 vite-plugin-electron.log 可以通过配置关闭吗？有时候只是启动项目，但并没有修改代码，也会导致有 git 未提交的提示。

这是个 BUG 😅，只会在 Windows 下出现，我用的是 Mac 没发现；下个版本会处理掉。
