### ISSUE TITLE
Error in log: "The main field in package.json may be incorrect, which causes the App to fail to start."

### ISSUE THREAD

**Issue by PAXANDDOS** [electron-vite/vite-plugin-electron#41]
While working in `electron-vite-react` the following message in the `vite-plugin-electron.log` is repeated on each build:

```log
[24/07/2022, 14:09:15]
  Command: "vite serve".
  The main field in package.json may be incorrect, which causes the App to fail to start.
  File build path: "C:\Users\PAXANDDOS\Desktop\electron-vite-react\dist\electron\main\index.js".
  Recommended main value: "C:\Users\PAXANDDOS\Desktop\electron-vite-react\dist\electron\main\index.js".
```

Even though it looks like something that would break the application, it works as intended 🤔 
The issue exists both on `Vite` `v3` and `v2`, so it should be something in the plugin

**Comment by caoxiemeihao** [comment]
The BUG will resolved in `v0.8.2` 😅
Because I am using a Mac, the duration will make such a mistake 😖
https://github.com/electron-vite/vite-plugin-electron/commit/0016d52e2157e3bda7732168cd60af88ba8aa9b0
