### ISSUE TITLE
PNPM version number does not match properly due to version release

### ISSUE THREAD

**Issue by yxswy** [electron-vite/vite-plugin-electron#43]
PNPM version number does not match properly due to version release

**Comment by caoxiemeihao** [comment]
Thanks feedback! 😅
Now, `vite-plugin-electron` ![NPM version](https://img.shields.io/npm/v/vite-plugin-electron.svg) is available.

**Comment by yxswy** [comment]
chinese，我也是今天下午在做electron+vite的时候，明明是好的，换个文件夹就坏了，我还以为是我运气很差呢，哈哈

**Comment by yxswy** [comment]
thanks

**Comment by caoxiemeihao** [comment]
> chinese，我也是今天下午在做electron+vite的时候，明明是好的，换个文件夹就坏了，我还以为是我运气很差呢，哈哈

pnpm 我刚上手没多久，还没接入发布脚本。有时候习惯了就忘了 `npm publish` 和 `pnpm publish` 完全两码事儿。。。
