### ISSUE TITLE
Uncaught TypeError: Failed to construct 'URL': Invalid URL (vite 3)

### ISSUE THREAD

**Issue by yooouuri** [electron-vite/vite-plugin-electron#44]
> Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at index.2d20d94d.js:1:52013

<img width="517" alt="image" src="https://user-images.githubusercontent.com/12934957/180871822-4dbbe7a1-a485-4c00-8bc2-6e9fb15aa71d.png">

See build: https://gist.github.com/yooouuri/b1d1706f7708865a359680bb3fdfbe0a#file-index-2d20d94d-js-L2745

It tries to generate a URL:

```
const nl = "" + new URL("electron.fe1dfbad.png", Wn.url).href
```

But, 

```
const Wn = {};
```

There is no `.url` on `Wn`...

https://gist.github.com/yooouuri/b1d1706f7708865a359680bb3fdfbe0a#file-index-2d20d94d-js-L2

Happens when I upgrade vite to version 3.

How to reproduce:

```bash
git clone https://github.com/yooouuri/electron-vite-vue
cd electron-vite-vue
yarn install
yarn build
```

Open the binary in the release folder, for me its the .app (Mac OS).

**Comment by yooouuri** [comment]
Guess https://github.com/electron-vite/electron-vite-vue/issues/212 is related

**Comment by caoxiemeihao** [comment]
Thanks for your feedback and reason analysis.
I have noticed this issue, I will try to fix it via a plugin or by submitting a PR to Vite.

At present, you can use `vite@2.x` to avoid this BUG.
