### ISSUE TITLE
TypeError: electron is not a function

### ISSUE THREAD

**Issue by denganjia** [electron-vite/vite-plugin-electron#45]
using Vite`3.0.3`

**Comment by denganjia** [comment]
![image](https://user-images.githubusercontent.com/46669447/181410348-62859005-ee99-4d44-8d11-d7fc754f3a5e.png)

**Comment by caoxiemeihao** [comment]
Are kidding me?

**Comment by denganjia** [comment]
> Are kidding me?
我也不知道咋回事😭，我用的包管理器是 `pnpm`，有没有交流群，大佬

**Comment by denganjia** [comment]
> > Are kidding me?
> > 我也不知道咋回事😭，我用的包管理器是 `pnpm`，有没有交流群，大佬

![image](https://user-images.githubusercontent.com/46669447/181414514-ae143f42-0e66-4c60-a1b8-82b88a61556d.png)

**Comment by denganjia** [comment]
我把Vite2、vite-plugin-electron升级到vite3 可以用，但是我创建一个行的 vite3+vite-plugin-electron就不行😖

**Comment by caoxiemeihao** [comment]
换成 yarn 或者 npm 试试看
交流群有的，不过我不在群里 😅

**Comment by denganjia** [comment]
![image](https://user-images.githubusercontent.com/46669447/181429154-09a562f4-3581-484c-a54f-62b0e18f4143.png)
![image](https://user-images.githubusercontent.com/46669447/181429207-b1281ad0-9910-4ab5-a51e-8da12d3c8149.png)
yarn npm pnpm 都是一样的😰

**Comment by caoxiemeihao** [comment]
啥都没干，clone 下来就报错？
你要改了改了东西，就提供个 Deom 放上来。

**Comment by caoxiemeihao** [comment]
@denganjia 
Can you provide a minimal Demo to put on Github, I just found the same problem in Vite's Issues.
*你那个报错的 Demo 方不方便放到 Github 上面来我看看，我刚在 Vite 的 Issues 中发现了同样的问题*

**Comment by BalotT** [comment]
vite 3.0.0 vite.config.ts，除了vue(),vueJsx(),其他的插件只要是function引入都会报错

**Comment by BalotT** [comment]
> 我把Vite2、vite-plugin-electron升级到vite3 可以用，但是我创建一个新的 vite3+vite-plugin-electron就不行😖

vite版本问题，降低到2.9就不回有问题了，原因还不知道

**Comment by caoxiemeihao** [comment]
@BalotT 
Vite3.0 一堆问题，到是你的问题我昨天用 3.0 试了下没复现
你能给个最小化复现 Demo 吗

**Comment by BalotT** [comment]
@caoxiemeihao 
https://github.com/BalotT/Vite_3.0_demo.git
vite init 最新版本 npm 移步 vite.config.ts

**Comment by BalotT** [comment]
> 

删掉package.json 中的 "type": "module"配置

**Comment by caoxiemeihao** [comment]
> 删掉package.json 中的 "type": "module"配置

可以的 😂，那要给插件提供 `exports` 字段避开这个问题了。因为大部分人写插件都只会考虑 CJS 场景

**Comment by caoxiemeihao** [comment]
`v0.8.5` 将会支持 `type: module`
