### ISSUE TITLE
electron is not a function

### ISSUE THREAD

**Issue by zhanghu12138** [electron-vite/vite-plugin-electron#47]
While I use `vite-plugin-electron` with Vite offical [template-vue-ts](https://github.com/vitejs/vite/tree/main/packages/create-vite/template-vue-ts), getting the following errors.

*使用vite 初始模板，在vite.config.ts中调用会报错*

![image](https://user-images.githubusercontent.com/41420199/182285477-e4958fe6-7fd3-41c4-9e1d-c898b8a6cb69.png)

![image](https://user-images.githubusercontent.com/41420199/182285697-f4dde58e-717d-4a97-ae34-cdcb6d5207c7.png)
![image](https://user-images.githubusercontent.com/41420199/182285722-a74e171b-bc7a-475e-95e4-95a4fd6186e9.png)

**Comment by caoxiemeihao** [comment]
把 `package.json` 中的 `"type": "module"` 去掉

**Comment by zhanghu12138** [comment]
已解决，谢谢大佬

**Comment by Y-qwq** [comment]
> You can try remove `"type": "module"` in `package.json` fix it.
> 
> _把 `package.json` 中的 `"type": "module"` 去掉_

@caoxiemeihao 为什么不是多支持一种导出类型呢？
因为一个插件而修改整个项目的默认 `type` 感觉是一件不太合理的事情

**Comment by Y-qwq** [comment]
> @Y-qwq `v0.9.4` 支持 `cjs`, `esm` 两种格式导出，等待 `vite@3.1.5` 的新功能上来就发。 其次支持 `esm` 没有用，因为 Electron 不支持 `esm`，反正 `v0.9.4` 加上 `esm` 省的用户总觉得好像我不支持 `esm` 似的。
> 
> https://github.com/electron-vite/vite-plugin-electron/tree/v0.9.4

好吧，是我之前配项目的时候下意识认为 Electron 已经支持了 `esm` 了
后面通过针对 Electron 主进程的代码打成 `cjs` 的方式解决了
