### ISSUE TITLE
absolute paths not work

### ISSUE THREAD

**Issue by nguyenshort** [electron-vite/vite-plugin-electron#53]
Hi, I have some code shared between Vue and Electron like interface, enum...
I am using vite-tsconfig-paths for load resolve alias

anything is working perfectly in Vue app...but that is not working if I try to import anything to any file in the electron folder

```
[vite]: Rollup failed to resolve import "@shared/api/main" from "electron/preload/modules/main.module.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

<img width="263" alt="Ảnh chụp Màn hình 2022-08-09 lúc 03 19 20" src="https://user-images.githubusercontent.com/55306331/183507076-ed1f7781-4168-4be2-884d-ee3e21a540e8.png">

> tsConfigPaths
```
tsconfigPaths({
      loose: true
}),
```

> paths
```
"paths": {
      "#electron/*": [
        "./electron/*"
    ]
}
```

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction Demo? I will try to Debug it.
