### ISSUE TITLE
win11 vite-plugin-electron.log

### ISSUE THREAD

**Issue by Hunlongyu** [electron-vite/vite-plugin-electron#56]
0.7.5 版本说会关闭，但是现在 0.9.0 还是存在这个问题。
Windows11 系统下，还是会自动生成 log 文件

**Comment by caoxiemeihao** [comment]
=。= 这个我回头找个 Windows 电脑试试看。

**Comment by Hunlongyu** [comment]
![image](https://user-images.githubusercontent.com/15273630/185334417-dc4b8327-a612-45e8-a659-7b9683e5b41f.png)

**Comment by caoxiemeihao** [comment]
这个不适合放到 `termianl` 中，只能算个警告类型。
如果你的 `main` 字段不对，之后的在 `electron-builder` 的 `termianl` 中报错。
