### ISSUE TITLE
Failed to resolve import "@/composables" from "src/components/Footer.vue". Does the file exist?

### ISSUE THREAD

**Issue by 251205668** [electron-vite/vite-plugin-electron#59]
`error screens`
<img width="815" alt="image" src="https://user-images.githubusercontent.com/46418596/186649038-84263e91-3eed-40ec-a0eb-40c2c179b5af.png">
`resolve config`
<img width="739" alt="image" src="https://user-images.githubusercontent.com/46418596/186649112-94d86c0e-78bb-4898-9f18-d869e8000e82.png">

`electron config`
<img width="673" alt="image" src="https://user-images.githubusercontent.com/46418596/186649169-ad73265e-6adf-4fb4-b7c3-b43e6911f119.png">
`tsconfig.json`
<img width="759" alt="image" src="https://user-images.githubusercontent.com/46418596/186649248-67f74f91-4573-4971-9bf7-945884f6aaa9.png">

**Comment by 251205668** [comment]
`router.ts`
<img width="903" alt="image" src="https://user-images.githubusercontent.com/46418596/186650519-0dbfe925-ee60-4fdb-abde-57a220faa985.png">

**Comment by caoxiemeihao** [comment]
You can try use [vite-plugin-dynamic-import](https://github.com/vite-plugin/vite-plugin-dynamic-import)
