### ISSUE TITLE
[🐞] exports is not defined

### ISSUE THREAD

**Issue by shunyue1320** [electron-vite/vite-plugin-electron#6]
[/renderer/index.js 90 行](https://github.com/electron-vite/vite-plugin-electron/blob/main/renderer/index.js/#L90) 如项目内存在动态引入的情况，这将导致 vite 打包后运行报错
如：
```
import('./abc.vue') 
```
运行后报错: exports is not defined

其原因是生成的代码为：
```
"use strict";Object.defineProperties(exports,{__esModule:...
```

**Comment by shunyue1320** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/47295879/171554015-787bb587-a1b9-4e8e-8663-81c6d7fa49c7.png">

**Comment by shunyue1320** [comment]
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/47295879/171554123-05e807ce-7216-499c-b176-9897a6031936.png">

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/electron-vite-vue/issues/103#issuecomment-1098662928 😄

**Comment by shunyue1320** [comment]
Oh, thanks !

**Comment by caoxiemeihao** [comment]
Thank you to find the cause of the BUG, I considering to integrate the fix-method into plugin by default. 😄
