### ISSUE TITLE
Additional arguments when executing vite are lost

### ISSUE THREAD

**Issue by cmitjans-at-wiris** [electron-vite/vite-plugin-electron#60]
When executing `yarn vite` with custom parameters, these are lost. Looking at the source code, electron is only launched with `--no-sandbox`.

https://github.com/electron-vite/vite-plugin-electron/blob/949fd99df8b528de817f38c5a131b081be879c85/packages/electron/src/serve.ts#L125

Is there a way to pass custom arguments to the electron application?

I want to be able to launch vite with: `yarn vite -f ~/path/to/file`

**Comment by caoxiemeihao** [comment]
You can try to custom start Electron
https://github.com/electron-vite/vite-plugin-electron/blob/b0f2c9664530c1aa431ab2694fc01526d6dd5498/playground/usecase-in-main/vite.config.ts#L21-L32

**Comment by cmitjans-at-wiris** [comment]
It worked!

To clarify, arguments have to be passed to `spawn`:

```
spawn(`${__dirname}/node_modules/.bin/electron`, ['.', '--no-sandbox', process.argv]
```

**Comment by nukeop** [comment]
Would you happen to know how that technique affects startup times?
And is it possible to pass a flag or something that would make this behavior the default in the plugin, instead of having to override onstart?

**Comment by caoxiemeihao** [comment]
> That works in dev mode, but it runs the app when building it, and the arguments are still lost in the packaged version.

About arguments, you can see 👉 https://www.electronjs.org/docs/latest/api/command-line#commandlineappendargumentvalue
