### ISSUE TITLE
electron is not a function

### ISSUE THREAD

**Issue by vhsch** [electron-vite/vite-plugin-electron#65]
![image](https://user-images.githubusercontent.com/102227399/187234499-4ccd1c84-72f0-43bb-bd1f-fdf6d1369be5.png)
[vite.config.ts.txt](https://github.com/electron-vite/vite-plugin-electron/files/9445761/vite.config.ts.txt)
all I found was a pr in mandarin that apparently fixed this exact issue but it's still here, I'm using version 0.9.2 FIY

**Comment by newholder** [comment]
also doesn't work for me. package.json type already set to module
