### ISSUE TITLE
Can't load sourcemaps for node modules in renderer

### ISSUE THREAD

**Issue by Jazcash** [electron-vite/vite-plugin-electron#70]
![image](https://user-images.githubusercontent.com/1434248/188221549-5ca9f4ce-a55b-491f-a144-948400adce50.png)

The modules themselves are working fine, and the sourcemaps are there in their respective folders in `node_modules`, but the renderer can't load them:

```
DevTools failed to load source map: Could not load content for http://127.0.0.1:5173/resolve.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

I didn't see any existing issues about this so maybe something to do with my setup:

```typescript
/* eslint-env node */

import vue from "@vitejs/plugin-vue";
import { join } from "path";
import { defineConfig } from "vite";
import renderer from "vite-plugin-electron-renderer";

const PACKAGE_ROOT = __dirname;

export default defineConfig({
    mode: process.env.MODE,
    root: PACKAGE_ROOT,
    envDir: process.cwd(),
    resolve: {
        alias: {
            "@": join(PACKAGE_ROOT, "src"),
            "!": join(PACKAGE_ROOT, "assets"),
            $: join(PACKAGE_ROOT, "../common"),
        },
    },
    base: "",
    server: {
        fs: {
            strict: true,
        },
    },
    build: {
        sourcemap: true,
        target: `es2022`,
        outDir: "dist",
        assetsDir: ".",
        rollupOptions: {
            input: join(PACKAGE_ROOT, "index.html"),
            output: {
                entryFileNames: "[name].cjs",
            },
        },
        emptyOutDir: true,
        reportCompressedSize: false,
        lib: {
            entry: "src/index.ts",
            formats: ["cjs"],
        },
    },
    plugins: [
        vue(),
        renderer({
            resolve() {
                return ["path", "fs", "stream", "os", "child_process", "node-fetch", "spring-map-parser", "tachyon-client", "sdfz-demo-parser", "octokit"];
            },
        }),
    ],
});
```

Any ideas how I can fix these, or otherwise hide the warnings?

**Comment by Jazcash** [comment]
Related: https://github.com/cawa-93/vite-electron-builder/issues/386

**Comment by Jazcash** [comment]
Ok, I found that installing https://github.com/vite-plugin/vite-plugin-esmodule fixes most of these warnings

**Comment by caoxiemeihao** [comment]
```js
renderer({
    resolve() {
        return ["path", "fs", "stream", "os", "child_process", "node-fetch", "spring-map-parser", "tachyon-client", "sdfz-demo-parser", "octokit"];
    },
}),
```

This will generate `require('module-name')`, maby `require()` can't load `sourceMap` properly.

**Comment by Jazcash** [comment]
Btw, I found that `esmodule` isn't actually fixing anything, it's just combining a lot of separate files into a single `index.js` which means when I said "fixes most of these warnings", all that was happening is all warnings for the separate files are just getting combined like this:

![image](https://user-images.githubusercontent.com/1434248/198157441-7f43984c-1792-418d-96e1-75a071c49df2.png)

Still no idea how to fix this unfortunately. Maybe the problem lies with `vite-plugin-electron-renderer` because it's not creating the `.map.js` files here?

![image](https://user-images.githubusercontent.com/1434248/198157650-00c63268-9ad1-415c-a16f-fc159bb9e1b8.png)

**Comment by caoxiemeihao** [comment]
The next version will be generate `.map.js` into `.vite-electron-renderer`

**Comment by Jazcash** [comment]
`electron-plugin-vite-renderer@0.10.3` now produces `.map` files for `type: "module"` entries, but not for `type: "commonjs"`:

![image](https://user-images.githubusercontent.com/1434248/201501346-d3ca50e0-6e97-417d-b352-170abb37e92d.png)

```
plugins: [
    vue(),
    renderer({
        nodeIntegration: true,
        optimizeDeps: {
            include: [
                { name: "path", type: "commonjs" },
                { name: "fs", type: "commonjs" },
                { name: "child_process", type: "commonjs" },
                { name: "stream", type: "commonjs" },
                { name: "os", type: "commonjs" },
                { name: "node-fetch", type: "module" },
                { name: "spring-map-parser", type: "commonjs" },
                { name: "better-sqlite3", type: "commonjs" },
                { name: "tachyon-client", type: "commonjs" },
                { name: "octokit", type: "commonjs" },
                { name: "axios", type: "commonjs" },
            ],
        },
    }),
    worker({
        nodeIntegrationInWorker: true,
    }),
]
```

**Comment by caoxiemeihao** [comment]
https://github.com/electron-vite/vite-plugin-electron/blob/646eaa60ea353f01bdfdbfc8165d01070d7fb9b6/packages/electron-renderer/src/optimizer.ts#L129-L140

`type: "module"` or `type: "commonjs"` ends up being just a cjs conversion file wrapped in a layer, it is a new file and not converted from any file.
