### ISSUE TITLE
file-url package doesn't work

### ISSUE THREAD

**Issue by astoilkov** [electron-vite/vite-plugin-electron#75]
Sorry for bothering again. I caught another problem. https://github.com/sindresorhus/file-url package doesn't work.

It throws:
<img width="649" alt="CleanShot 2022-09-11 at 13 17 53@2x" src="https://user-images.githubusercontent.com/884810/189522417-91be0530-6538-4138-a98b-003810fb1545.png">

on line 12 of the module:
<img width="539" alt="CleanShot 2022-09-11 at 13 18 17@2x" src="https://user-images.githubusercontent.com/884810/189522429-15d4fd14-9876-431c-ae0f-227b57101508.png">

**Comment by caoxiemeihao** [comment]
Use in Renderer.
https://github.com/electron-vite/vite-plugin-electron/blob/58d3697500e248c5c8485f517b8c9080202c193f/playground/usecase-in-renderer/vite.config.ts#L37

**Comment by astoilkov** [comment]
Hmm. I'm a little confused. Why isn't this automatic? Let me explain my thinking:
- Vite has great defaults. One of the reasons it's better than Webpack is that it's a lot simpler to use. I feel like this also can be automatic.
- ESM packages can be detected by reading the `package.json` file and its `"type": "module"` value.

One additional question as I don't understand it. Why doing `import path from 'path'` in my own source code works but when a third-party mode does it it doesn't? Am I correct about this?

P.S. I'm closing this issue because my comment goes out of topic. There isn't an issue here, just a possible improvement.

**Comment by astoilkov** [comment]
One more point: I actually don't need to specify a list of ESM modules in our current Webpack configuration.

I am diving a little deeper into this because we have a lot of ESM modules and I don't even know how to get a list of all of them quickly. Some things might be broken but I don't even know until the specific module is executed.

**Comment by caoxiemeihao** [comment]
There is an easier way.

```diff
export default {
+ optimizeDeps: {
+   exclude: ['file-url']
+ }
}
```

**Comment by astoilkov** [comment]
This still requires me to list all ESM packages. As ESM packages are on the rise I'm looking for a solution that won't require me to update `vite.config` every time I install an ESM package. I would also need a way to find out all the ESM packages I'm currently using.

I'm thinking about going through all node_modules and finding out all the ESM packages but this would require extra code and maintenance.
