### ISSUE TITLE
Can not find entry file during build phase 

### ISSUE THREAD

**Issue by JunzheFan** [electron-vite/vite-plugin-electron#78]
I got this error message when tring to build a NSIS installer using electron-builder

Application entry file "dist\electron\main\index.js" in the "D:\Vue-electron\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=

Here is the snippet in the vite.config file,  how to properly configure that `entry` field when packaing the app ? 
`   electron({
      main: {
        entry: "electron/main/index.ts",
        vite: {
          build: {
            // For Debug
            sourcemap: true,
            outDir: "dist/electron/main",
          },
        },
      }`

**Comment by JunzheFan** [comment]
```
    "files": [
      "dist/electron/**/*",
    ],
```
OK it's working after  I added the above code in the build property in the package.json,  but when I run the installed app, the screen was empty/blank,  I supposed it didn't find the index.html ?  I was using the vue-vite-electron template directly to create my app

**Comment by caoxiemeihao** [comment]
Please make sure the `main` option in `package.json` has the correct path.

```json
"files": [
  "dist",
],
```
