### ISSUE TITLE
Error launching app, Unable to find Election app at...

### ISSUE THREAD

**Issue by Levelangel** [electron-vite/vite-plugin-electron#79]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/16518190/191512136-43ebfc47-7940-474a-8358-8228c97a8442.png">

follow all the step in gif in readme
跟着Readme中gif图片的步骤，一模一样

**Comment by Levelangel** [comment]
no error in console
控制台没有报错

**Comment by caoxiemeihao** [comment]
package.json` 中的 `main` 字段路径不对
