### ISSUE TITLE
aliases in main?

### ISSUE THREAD

**Issue by alexpineda** [electron-vite/vite-plugin-electron#80]
I'm attempting to port my electron-webpack project over to vite using vite-plugin-electron. https://github.com/imbateam-gg/titan-reactor

I'd like to retain the structure `src/renderer`, `src/common`, `src/main`. With both `renderer` and `main` having aliases to common for shared utilities and types. 

There is a resolve option in `main` for this plugin but it seems to overwrite the previous configuration.

**Comment by caoxiemeihao** [comment]
```ts
export default {
  plugins: [
    electron({
      main: {
        entry: 'electron/main/index.ts',
        vite: {
          resolve: {
            // Electron-Main alias
            alias: {},
          },
        },
      },
    }),
  ],
  resolve: {
    // Electron-Renderer alias
    alias: {},
  },
}
```
