### ISSUE TITLE
在win的环境中，怎么改变软件的桌面的快捷方式图标

### ISSUE THREAD

**Issue by wfxt0911** [electron-vite/vite-plugin-electron#84]
在win的环境中，怎么改变软件的桌面的快捷方式图标？，现在的图标都是默认的图标
![image](https://user-images.githubusercontent.com/84564199/192931220-7c8fba86-6016-4bc8-ab6f-4baad5147488.png)

**Comment by wfxt0911** [comment]
目前的vite配置如下，请教下如何更改图标
![image](https://user-images.githubusercontent.com/84564199/192931309-8feedc6f-0875-43db-9ff7-beebeae1933b.png)

**Comment by caoxiemeihao** [comment]
去看下 https://github.com/electron-vite/electron-vite-react 怎么配置的
