### ISSUE TITLE
安装了这个插件之后，为什么运行vite也会运行electron . ？只想打开网页

### ISSUE THREAD

**Issue by zhangzhi93** [electron-vite/vite-plugin-electron#88]
安装了这个插件之后，为什么运行vite也会运行electron . ？只想打开网页

**Comment by zhangzhi93** [comment]
> 那你装这个插件干嘛？

要区分啊，有时候只打包网页，有时候打包exe。调试网页的时候，直接就运行electron了

**Comment by caoxiemeihao** [comment]
READM 中有个 custom start 的说明

**Comment by zhangzhi93** [comment]
> READM 中有个 custom start 的说明
`
"vite": "^3.1.8",
"vite-plugin-electron": "^0.10.0"
`
`
electron({
        onstart: undefined,
        entry: ['electron/main/index.js', 'electron/preload/index.js'],
        vite: {
          build: {
            outDir: path.resolve(__dirname, './build'),
          },
        },
      })
`

根据文档配置之后，运行vite后还是会启动electron，是哪里配置错误了吗？ 并且当entry配置成数组的时候会报错，执行不成功。`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array` 这个错误

**Comment by zhangzhi93** [comment]
> READM 中有个 custom start 的说明
`
"vite": "^3.1.8",
"vite-plugin-electron": "^0.10.0"
`
`
electron({
        onstart: undefined,
        entry: ['electron/main/index.js', 'electron/preload/index.js'],
        vite: {
          build: {
            outDir: path.resolve(__dirname, './build'),
          },
        },
      })
`

根据文档配置之后，运行vite后还是会启动electron，是哪里配置错误了吗？ 并且当entry配置成数组的时候会报错，执行不成功。`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array` 这个错误

**Comment by zhangzhi93** [comment]
> READM 中有个 custom start 的说明

```
"vite": "^3.1.8", 
"vite-plugin-electron": "^0.10.0"
```

```
electron({
  onstart: undefined,
  entry: ['electron/main/index.js', 'electron/preload/index.js'], 
  vite: { 
     build: { 
        outDir: path.resolve(__dirname, './build'),
     },
  }, 
})
```

根据文档配置之后，运行vite后还是会启动electron，是哪里配置错误了吗？ 并且当entry配置成数组的时候会报错，执行不成功。`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array` 这个错误

**Comment by caoxiemeihao** [comment]
Vite 最低要求 `3.2.0`
看 Demo https://github.com/electron-vite/vite-plugin-electron/tree/main/examples/custom-start-electron-app

**Comment by zhangzhi93** [comment]
> Vite 最低要求 `3.2.0` 看 Demo https://github.com/electron-vite/vite-plugin-electron/tree/main/examples/custom-start-electron-app

3.2.0还是beta版本呢，如果不用3.2.0，要退vite-plugin-electron到0.9.3吗？0.9.3之前没有配onstart也会自动启动electron

**Comment by caoxiemeihao** [comment]
哪个版本都有自定义启动，就是写法不一样
你自己翻之前的版本看看 READ ME
