### ISSUE TITLE
Could not resolve peer dependency vite: 3.2.0

### ISSUE THREAD

**Issue by Hafiidz** [electron-vite/vite-plugin-electron#90]
```
npm WARN Could not resolve dependency:
npm WARN peer vite@">=3.2.0" from vite-plugin-electron@0.10.0
```

I am having another issue (require is not define in browser) and trying to update this plugin to latest version. However, there is a problem found with peer dependency, as attached above. I have checked, vite only has 3.1.7 as latest version. 3.2.**0-beta.0** is available but is there a problem for npm to read that beta portion?

**Comment by caoxiemeihao** [comment]
You can use `0.9.x`

**Comment by Hafiidz** [comment]
First of all, thanks for the reply and the great plugin here. Love it. Yes, I am currently using `0.9.x`, but encountered a weird bug where in browser mode (electron is working fine) I am encountering the following error:

![image](https://user-images.githubusercontent.com/3688500/195000299-49c68315-af58-4640-8738-6c7e31c02579.png)
![image](https://user-images.githubusercontent.com/3688500/195000367-d4b14a5c-eba2-46d4-a01c-d7a698a09178.png)

Saw the 0.10.0 release might address this and try to get it. Do you have any other suggestion to address the error above ya?

**Comment by Hafiidz** [comment]
Additional info, I am also using `unplugin-icons` and `@iconify/json` which is why there is additional folder there, but when after further testing, even with those two plugins disabled, I still have this problem, which I think is maybe related to electron-vite-plugin. Maybe.

**Comment by caoxiemeihao** [comment]
`require is not defined`, remove `renderer: {}` option to resolve it.
Or you can use `vite-plugin-electron-renderer@0.10.0`

You can see this PR https://github.com/electron-vite/vite-plugin-electron/pull/89

<img width="862" alt="image" src="https://user-images.githubusercontent.com/26263658/195036949-85bc3758-7f37-4763-bbcd-d808756656f9.png">

**Comment by evil-shrike** [comment]
same here, the latest vite-plugin-electron can't be installed from npm:
Could not resolve dependency:
peer vite@">=3.2.0" from vite-plugin-electron@0.10.1

**Comment by Lizhiying123456** [comment]
+1

**Comment by Lizhiying123456** [comment]
当使用vite-plugin-electron@0.9.3的时候 在vite.config.ts中引入 配置完成后 启动项目会出现问题
![image](https://user-images.githubusercontent.com/93578059/196655256-742c3f51-098f-4d3b-88df-0312c194f55b.png)

**Comment by RealPhper** [comment]
看来n多人已经遇到了这个问题

**Comment by caoxiemeihao** [comment]
Will remove `3.2.0` needed in next version. Coming soon :)

**Comment by caoxiemeihao** [comment]
Hi everyone! Upgrade `vite-plugin-electron` as `vite-plugin-electron-renderer` to `v0.10.2` :)
