### ISSUE TITLE
配置了paths，但是找不到module

### ISSUE THREAD

**Issue by SylowFeng** [electron-vite/vite-plugin-electron#95]
tsconfig.ts 中这样写的
```
"paths": {
      "@/*": [
        "./electron/main/*"
      ]
    },
```

vite.config.ts 中也配置了
```
resolve: {
    // 配置别名
    alias: {
      '@': path.join(__dirname,'./electron/main')
    }
  },
```

vscode中不会报错，但是run dev 就会报错
`Error: Cannot find module '@/windows'`

**Comment by SylowFeng** [comment]
我试了一下  src目录下都可用，但是electron目录就不行。

**Comment by caoxiemeihao** [comment]
```diff
export default{
  plugins: [
    electron({
      entry: 'electron/main.ts', 
+     vite: {
+       resolve: {
+         alias: {}
+       },
+     },
    }),
  ],
}
```

**Comment by axetroy** [comment]
> ```diff
> export default{
>   plugins: [
>     electron({
>       entry: 'electron/main.ts', 
> +     vite: {
> +       resolve: {
> +         alias: {}
> +       },
> +     },
>     }),
>   ],
> }
> ```

话说这个配置，不能从当前的 Vite 配置中读取的吗，这个显得很呆，要配置两遍。

不单单是 alias，还有 define 这样的设置，也是要配置两遍。

**Comment by caoxiemeihao** [comment]
> 话说这个配置，不能从当前的 Vite 配置中读取的吗，这个显得很呆，要配置两遍。

> 不单单是 alias，还有 define 这样的设置，也是要配置两遍。

呆不呆是小事儿，很多人会错误的把渲染进程，主进程的 alias 混用导致报错。到时候再来开个 ISSUES 我就不知道咋回了，再来个人说我的 alias 处理没有做进程区分之类的巴拉巴拉的。
