### ISSUE TITLE
pnpm add vite-electron-plugin missing peer esbuild@*

### ISSUE THREAD

**Issue by logeast** [electron-vite/vite-plugin-electron#99]
<img width="694" alt="image" src="https://user-images.githubusercontent.com/26041539/198558664-adf1b0c1-cbf5-441b-98e5-5c19f8d436df.png">

**Comment by caoxiemeihao** [comment]
npm i -D esbuild

**Comment by logeast** [comment]
Shouldn't it be given an explicit version number?

**Comment by caoxiemeihao** [comment]
There is no need to explicitly specify the version of `esbuild`, as Vite does.
https://github.com/vitejs/vite/blob/47a78db49740daee873525de90d0e44b19883771/packages/vite/package.json#L126-L132

**Comment by logeast** [comment]
So do I have to install esbuild manually, I don't think it's friendly.
